### PR TITLE
fix typo mistake in highlighting

### PR DESCRIPTION
**Pull request by makhov**
Sorry, my fault. Fix a little mistake in diff.tmpl

### CODE REVIEW

**Comment by phsmit** [comment]
:+1: Tested, looks good to me.

**Comment by makhov** [comment]
Fix last one bug

**Comment by phsmit** [comment]
Looks good! I'm not sure if it always makes sense to allow line blocks between different sides, especially not if we later get a "split-view" diff mode.

Anyway a small little bug still. If L2 is lower then R2 and I click on L2 first and click then on R2 this doesn't work. If I click on R2 first and then on L2 it does.

**Comment by makhov** [comment]
I can't represent it. It works fine to me.

**Comment by phsmit** [comment]
I sometimes hate browser caches. I hit Shift-F5 and now everything works perfectly! Sorry for the bother.

**Comment by Unknwon** [comment]
Thanks your PR!

**Pull request merged**
