### PR TITLE
Fix string format verbs

### PR DESCRIPTION
**Pull request by alunegov**
This PR fix string format verbs in log messages.

### CODE REVIEW

**Comment by alunegov** [comment]
To prevent this kind of errors we could rename log functions to have an "f" at the end and let **go vet** do the checks.

**Comment by LefsFlarey** [comment]
This is not a good idea. Traditional C++ variables like `%s` and `%d` denote `string` and `decimal/digit` types respectively and there is a reason why it is like that. We don't want strings in a decimal variable and vice versa and as such, another solution has to be implemented.

*On a site note though, what is this supposed to fix in the first place?*

**Comment by alunegov** [comment]
Originally this PR fixes wrong format verbs. For example, in models/update.go were used **%d** for **opts.PusherName**, which is actually a string. In http.log this produce [I] Reference '...' has been deleted from '...' by **%!d(string=...)**.

**Comment by LefsFlarey** [comment]
I'm not too sure if this is right or wrong, maybe @Unknwon could give his insight on this...

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
