### PR TITLE
allow http push by token - #842

### PR DESCRIPTION
**Pull request by compressed**
Hi,
Here's my attempt to allow pushing by token. Not sure if there were any other places to change.

Let me know how it looks.

Thanks!

Edit - sent to gogs/master instead of gogs/dev by accident. Fixed now.

### CODE REVIEW

**Comment by Unknwon** [comment]
Very late reply, sorry!

But for this feature, if no other security concerns, I think change this single line would solve the problem: https://github.com/gogits/gogs/blob/master/modules/auth/auth.go#L30 

What are your thoughts?

**Comment by compressed** [comment]
No worries!

@Unknwon - that would be great if we can make a single line change. I'm not sure though what that change would be.... Can you help?

It seems when I clone using an API key as the user name, the API key is within the http Basic header, which means the encoding needs to be applied. There won't be anything in the token header. Also, it seems even if we change `auth.go` to return the proper token.Uid from Basic auth, it still ends up going to `http.go` where it again goes through the `askAuth` check which will ultimately not find the `authUsername` (because it is the token not user name). Hopefully I'm missing something here!

**Comment by compressed** [comment]
ping @Unknwon

**Comment by Unknwon** [comment]
@compressed I'm here, many PRs are left in my vocation, I'm working on these in order, so will be soon help on this! 

Sorry about this!

**Comment by Unknwon** [comment]
> It seems when I clone using an API key as the user name, the API key is within the http Basic header, which means the encoding needs to be applied. There won't be anything in the token header. Also, it seems even if we change auth.go to return the proper token.Uid from Basic auth, it still ends up going to http.go where it again goes through the askAuth check which will ultimately not find the authUsername (because it is the token not user name). Hopefully I'm missing something here!

You're absolutely right!

Just a note that list all tokens isn't a good way when token number gets very large. 

I'll merge right now, but will push some fixes soon after.

Thanks for your patient and work!

**Comment by compressed** [comment]
Great, thanks a lot! Yes, I realized iterating through the tokens wasn't a good idea, but I never updated PR. Thanks for doing that!

**Comment by Unknwon** [comment]
@compressed , no problem, my pleasure!

**Pull request merged**
