### PR TITLE
Add PAM authentication

### PR DESCRIPTION
**Pull request by nacho**
We've done this patch to add the PAM authentication and it seems to work for us. There are a couple of issues though:
1. we don't know how to make it conditional for just linux servers
2. the new label for some reason is not translated

### CODE REVIEW

**Comment by pbor** [comment]
I fixed the conditional compilation, you now need -tags pam, otherwise you get a stub that always refuses auth.

**Comment by lunny** [comment]
Discuss:  use `pam_linux.go` or `+build linux` and `+build !linux` to instead `+build pam`. Because Go compiler will recognize the conditional compiling `linux`. Then for linux binary, it will include the pam support and others will not.

**Comment by pbor** [comment]
I used +build pam because pam is available also on osx. But I can change it as you prefer.

**Comment by lunny** [comment]
OK. Then maybe you can use `+build !windows`.

**Comment by nacho** [comment]
Changed. Do you have any other comments?

**Comment by lunny** [comment]
No. But the CI report it not build success. Could you checked if it has conflicts with other pr?

**Comment by nacho** [comment]
Maybe because the build now depends on pam-devel?

**Comment by lunny** [comment]
`pam-devel` is a c++ library?

**Comment by nacho** [comment]
It is a C library see https://git.fedorahosted.org/cgit/linux-pam.git/

**Comment by nacho** [comment]
Is there a way to tell to travis that now we depend on that pam library?

**Comment by nacho** [comment]
It seems to build now. I added libpam-dev to travis.

**Comment by lunny** [comment]
Thanks.

**Comment by nacho** [comment]
Thanks to you for the quick review.

**Comment by Unknwon** [comment]
Hi @nacho , thanks your work again!

I just made one change about this PR:

I noticed some linux versions do not come with required C header files, so make install process `go-get`able, I change to use build tag `pam` to support PAM auth: https://github.com/gogits/gogs/commit/81adbe17caf4ff8d7fc920dfe661640ab248ad12 , also updated `.travis.yml` file as an example of how to use build tag.

Best regards,
Jiahua Chen

**Comment by pbor** [comment]
@Unknwon , thanks, having a pam tag is ok.

It would be great if future binary releases are built with the tag enabled

**Comment by Unknwon** [comment]
@pbor It would be certain that binary releases are built with the tag enabled. :dizzy:

**Pull request merged**
