### PR TITLE
[WIP] GPG signature verification

### PR DESCRIPTION
**Pull request by sapk**
I start to implement API and extracting information for the git cli via gogits/git-module#13. It may need to add some little parts to the gogits/go-gogs-client to be more specific to GPG key api.

Related to gogits/gogs#2321 and gogits/gogs#2981

Branch : [sapk/gogs:implement-gpg-keys-api](/sapk/gogs/tree/implement-gpg-keys-api)

### CODE REVIEW

**Comment by stevenroose** [comment]
@sapk Make sure you are not doing double work here. @bkcsoft indicates two weeks ago to be working on this too: https://github.com/gogits/gogs/issues/2321#issuecomment-218274684

**Comment by bkcsoft** [comment]
I have not started on that one yet, and this one does verification which
mine wouldn't (only stupidly show that it had been signed)

WRT people working on things. PR fast, mark it WIP. If no PR for a feature
exists, no one is working on it :laughing:

**Comment by stevenroose** [comment]
@bkcsoft Totally of topic, but it would be nice to have people link to the branch where they are working on it (I know it's visible, but not clickable), so that people could file PRs to that feature's branch to contribute :) Just imagining an ideal world of decentralized collaboration ;)

Good to see you are also actively maintaining this project next to Unknwon!

**Comment by bkcsoft** [comment]
@stevenroose I had not noticed that they were not clickable :laughing: Yes, link to branch would be nice (even though the PR will update when the branch is pushed to...)

**Comment by bkcsoft** [comment]
@sapk still working on this? I found [OpenPGP.js](https://github.com/openpgpjs/openpgpjs) and realized that verification could be done in the frontend to off-load the backend (not that it requires off-loading, but nice to keep the load in the frontend if it's possible :laughing: ) Thoughts?

**Comment by sapk** [comment]
I didn't tackle the part of the of the verification and I didn't have some time to go further but i will re-put myself on it on the next days. Doing it in the front-end could done easely. it just need the API to get the user public key from gogs like https://developer.github.com/v3/users/keys/. ON the other i don't thinks it would be to much work for the backen to do it. I have to think about it but at first at will implement the API because in both case there will be needed (or at least usefull)

**Comment by ekozan** [comment]
any news ? :)

**Comment by sapk** [comment]
sadly no time yet :-(

**Comment by ekozan** [comment]
??

**Comment by lesderid** [comment]
@Unknwon why did you close this?

**Comment by bkcsoft** [comment]
@sapk not sure why this was closed, but could you maybe send this PR to gitea as well? 🙂

**Comment by stevenroose** [comment]
I'd kindly invite you to join the Gitea community where a more open approach to community-driven software development is used :)

**Pull request closed without merging**
