### PR TITLE
[Feature] Unified Diff-view

### LINKED ISSUE #1925: Side-by-side diff view
I don't know how hard it would be to implement it. Feel free to close this issue if you don't intent to bring this to Gogs.

Side-by-side diff is supported by GitHub and GitLab, and I think it is much easier to see a what changed in a commit. Don't know what tool they use, though.

sidebyside3

sidebyside2

### PR DESCRIPTION
**Pull request by bkcsoft**
Implemented Unified Diff-view. Inline/Unified is selectable with a button (Fixes #1925)

2015-12-26-140919_1600x900_scrot
2015-12-26-114558_1600x900_scrot

### CODE REVIEW

**Comment by bkcsoft** [comment]
Don't merge it's broken! :smiley:

**Comment by bkcsoft** [comment]
Now it seems to work. Though I'd like someone else to test as well :)

**Comment by Unknwon** [comment]
Thanks, but wrong PR name?

**Comment by andreynering** [comment]
@bkcsoft Nice job. I built it here and it seems to be working fine.

There was a file in a commit that showed one above the another, instead of side-by-side:



I didn't take a deeper look on code, though.

**Comment by bkcsoft** [comment]
@andreynering that shouldn't be possible :/ could you paste the relevant (the offending table) html-code?

**Comment by bkcsoft** [comment]
@unknwon could you clarify? I read the contribution best practices and didnct find anything about PR names

Though I fiddled with gogs.css directly, I'll change it in the less-files instead later tonight :) (unless I fall asleep, in which case I'll change tomorrow)

**Comment by Unknwon** [comment]
Isn't this is about side by side diff? Unified diff is the one currently working.

**Comment by andreynering** [comment]
> That shouldn't be possible :/ could you paste the relevant (the offending table) html-code?

Here: https://gist.githubusercontent.com/andreynering/5cf775650f363dd83f6b/raw/7be776aaa2085651bc29d66b489aa50ed276388b/diff.html

What I did was push Gogs to Gogs :stuck_out_tongue: and open this commit: https://github.com/gogits/gogs/commit/40f3142264aa20103ba2c6375b344e491cff27f5

> Isn't this is about side by side diff? Unified diff is the one currently working.

We are talking about side-by-side diff. @bkcsoft called it "unified" but I think "side-by-side" would be more coerent with Github and Gitlab.

**Comment by bkcsoft** [comment]
@andreynering odd, that seems like a template-bug (it really shouldn't happen :P ) I'll see if I can replicate it

@Unknwon you are corrent, it has the wrong name. I mistook unified for split, I'll change the name and rebase the commits into feature/split-diff instead and create a new PR :)

**Comment by bkcsoft** [comment]
@Unknwon @andreynering Github calls it Split diff-view and GitLab calls it Side-by-Side diff-view, I'm probably gonna call it "Split diff-view" since it's less typing than "Side-by-Side diff-view" ^.^

**Comment by Unknwon** [comment]
I prefer `Split diff-view` too.

**Comment by Unknwon** [comment]
Also, please read https://github.com/gogits/gogs/wiki/Contributing-Code#final-checks

**Comment by bkcsoft** [comment]
Closing this in favour of #2296

**Pull request closed without merging**
