### PR TITLE
Started to integrate DroneCI

### PR DESCRIPTION
**Pull request by tboerger**
**Obsoletes https://github.com/gogits/gogs/pull/2010 as i messed up the history of it and it have been made against master.**

### CODE REVIEW

**Comment by tboerger** [comment]
@Unknwon drone should work fine, but I still get errors on 1.3 and 1.4 as you can see on http://github.dronehippie.de/gogits/gogs/13.

**Comment by Unknwon** [comment]
1.3 is no longer supported, so it fails.

I'm still looking the error on 1.4.

**Comment by Unknwon** [comment]
Maybe go 1.4 does not have `-ldflags`?

**Comment by tboerger** [comment]
> Maybe go 1.4 does not have -ldflags?

I don't know... I think you are building it with the flags or not? Should i just enable 1.5 for now?

**Comment by Unknwon** [comment]
Yes, only 1.5 should be good I think.

**Comment by tboerger** [comment]
I have disabled the matrix build for now as it's not needed for a single go version.

**Comment by tboerger** [comment]
@Unknwon what do you need to finish this PR? Otherwise I would close that :)

**Comment by Unknwon** [comment]
What is the status of integration now... ?

**Comment by tboerger** [comment]
> What is the status of integration now... ?

From my side it looks pretty well, it's running tests (I can fix it, maybe it's just related to not using gopm), publish github release on tag push and should build latest, develop and tag docker containers.

The only thing that needs to be done by you is providing a .drone.sec file to add the values of the variables encrzpted to the repo, e.g. $$DOCKER_USERNAME, $$DOCKER_PASSWORD, $$DOCKER_EMAIL, $$GITHUB_TOKEN, $$EMAIL_HOST, $$EMAIL_PORT, $$EMAIL_USERNAME and $$EMAIL_PASSWORD.

This requires a .drone.sec.yml file with some content like this:

```yml
environment:
  - DOCKER_USERNAME=your_secret_username
  - DOCKER_PASSWORD=your_secret_password
  - DOCKER_EMAIL=your@email.address
  - GITHUB_TOKEN=your_secret_github_token
  - EMAIL_HOST=email.server.address
  - EMAIL_PORT=587
  - EMAIL_USERNAME=your@email.address
  - EMAIL_PASSWORD=your_secret_password
```

Afterwards download the drone-cli binary (find it at https://github.com/drone/drone-cli#installation) and execute the following command:

```
drone -t your_drone_ci_token -s http://github.dronehippie.de secure --checksum --in .drone.sec.yml --repo gogits/gogs
```

That way everything should be initialized. As a sidenote, everytime somebody changes the .drone.yml the secrets are getting invalidated as the secrets include a checksum of .drone.yml to prevent the leak of secret variables, for details look at http://readme.drone.io/usage/secrets/#checksums:0d943d142dc6bcdd2e544b095a49f72b

**Comment by Unknwon** [comment]
This is the screenshot for webhooks to your Drone instance, why it success and fails in somewhat a pattern?

image

**Comment by Unknwon** [comment]
I know some tests are 100% going to fail, will fix that.

**Comment by tboerger** [comment]
> This is the screenshot for webhooks to your Drone instance, why it success and fails in somewhat a pattern?

I have not seen that on my repos so far. Maybe we should ask @bradrydzewski if gogs can run on the official Drone version at https://beta.drone.io :)

**Comment by bradrydzewski** [comment]
@tboerger I am running the latest version of Gogs and Drone (both auto-upgrading with watchtower) and using Gogs extensively for private repos. There is a known issue with hooks for tags and branches described at https://github.com/drone/drone/issues/1412

There is a patch for the above issue that we're working through at https://github.com/drone/drone/pull/1448

I'm not sure if this is related to the above screenshot. It would be good to know if a) are there multiple drone hooks configured (old ones that need removed) and b) what type of hooks are failing, and are they tag or branch hooks? and c) the drone logs should provide some more detail if it isn't related to a or b

Hope that helps!

**Comment by bradrydzewski** [comment]
and yes, I'm happy to let you guys run gogs on beta.drone.io if you'd like

**Comment by Unknwon** [comment]
Thanks @bradrydzewski , just to clarify above screenshot is taken from GitHub webhook settings. 

Maybe @tboerger could find some logs for http://github.dronehippie.de/gogits/gogs ?

**Comment by Unknwon** [comment]
> and yes, I'm happy to let you guys run gogs on beta.drone.io if you'd like

:smile: this would be awesome, but I saw `Registration is closed`.

**Comment by tboerger** [comment]
> this would be awesome, but I saw Registration is closed.

@bradrydzewski just needs to add you to the whitelist :)

**Comment by tboerger** [comment]
@Unknwon if you click on the failing webhook requests you should see the type of payload. Are thos branch or tag refs?

**Comment by Unknwon** [comment]
```
X-GitHub-Delivery: fd09ce80-c9da-11e5-8ca5-cb178984cae8
X-GitHub-Event: push
```

**Comment by Unknwon** [comment]
BTW, the response code is `404`.

**Comment by tboerger** [comment]
Closing this because of lacking activity/interest.

**Pull request closed without merging**
