### PR TITLE
Use right semantic icon styles to fix star icon

### PR DESCRIPTION
**Pull request by sergey-dryabzhinsky**
Fix for #5208
Gogs: 0.11.48.0426

- Update font-awesome to latest 4.x version.
- Restore content for `fa-star(-o)` styles. Which is overridden by `semantic` styles.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks for the PR!

1. Please read https://github.com/gogits/gogs/wiki/Contributing-Code#coding-guidelines
2. Is updating Font Awesome to 4.7 not able to fix the `fa-star` style? But if the only solution is to override the style, I have no problem with that.

**Comment by sergey-dryabzhinsky** [comment]
1. Sorry, forgot about `less`. I'll remake PR.
2. Nope, updating FW to 4.7 not fixed styles.
  It's somehow messing with `semantic` syles.
  So I override some styles.

**Comment by sergey-dryabzhinsky** [comment]
Bump.

And no need to mess with css.

**Comment by Unknwon** [comment]
Can you take a screenshot of new change?

**Comment by sergey-dryabzhinsky** [comment]
Clean:


With dev-tools:

**Comment by Unknwon** [comment]
Thanks, how about icons after change (starred, unwatch)?

**Comment by sergey-dryabzhinsky** [comment]
Icons after change (starred, unwatch):

**Comment by sergey-dryabzhinsky** [comment]
Got these classes from: https://semantic-ui.com/elements/icon.html

**Comment by Unknwon** [comment]
LGTM.

**Pull request merged**
