### PR TITLE
Significantly enhanced LDAP support in Gogs

### PR DESCRIPTION
**Pull request by SergioBenitez**
Hi,

After a cluster of headaches working with LDAP in Gogs, I spent sometime revamping the Gogs LDAP auth module. Below is a brief summary (from the updated README) of the functionality in the new module:

This authentication module attempts to authorize and authenticate a user against an LDAP server. Like most LDAP authentication systems, this module does this in two steps. First, it queries the LDAP server using a Bind DN and searches for the user that is attempting to sign in. If the user is found, the module attempts to bind to the server using the user's supplied credentials. If this succeeds, the user has been authenticated, and the account information is retrieved and passed to the Gogs login infrastructure.

Here's an image of the new LDAP configuration form:
gogs-ldap

These changes should close the following issues:
#1257, #1238, #1145, #840, #472, #1429, #672 

This pull request also fixes several undocumented issues, such as a null pointer exception caused by https://github.com/gogits/gogs/blob/develop/models/login.go#L264, and adds logging to the LDAP authentication stream to aid in addressing LDAP configuration issues.

- Sergio

### CODE REVIEW

**Comment by lunny** [comment]
Looks great!

**Comment by Unknwon** [comment]
Thanks a lot!

But take a bit of time to review it.

**Comment by stevenroose** [comment]
Nice, you are a hero!

**Comment by SergioBenitez** [comment]
@Unknwon Let me know if you have any questions on the implementation or need me to rebase.

**Comment by Unknwon** [comment]
@SergioBenitez no problem. I'll let you know :)

**Comment by Unknwon** [comment]
PS: GitHub can merge with conflict on command line, so if no changes needed, I can still preform merge operation.

**Comment by Unknwon** [comment]
@SergioBenitez Hi, this PR has been merged, all looks awesome just one question, how is the compatibility between the new config option of LDAP and old ones(current ones that people are using)

**Comment by SergioBenitez** [comment]
@Unknwon They're not particularly compatible. Unless their LDAP server supports anonymous search requests and the filter they had set previously identified one user, the LDAP configuration will break. Since the previous filter was used in a different manner, this is unlikely to be the case, so I suspect most if not all LDAP users will need to reconfigure their Gog's LDAP parameters.

That being said, most users should find this form of LDAP configuration to be rather standard, and so reconfiguring their LDAP support should be rather easy. Furthermore, the README is rather detailed and should give even beginning LDAP users enough information to set this up.

Perhaps we should also update the LDAP information on the Gogs documentation using the image in the PR and the text in the README.

**Comment by Unknwon** [comment]
> @Unknwon They're not particularly compatible. Unless their LDAP server supports anonymous search requests and the filter they had set previously identified one user, the LDAP configuration will break. Since the previous filter was used in a different manner, this is unlikely to be the case, so I suspect most if not all LDAP users will need to reconfigure their Gog's LDAP parameters.

Thanks for the info.

> Perhaps we should also update the LDAP information on the Gogs documentation using the image in the PR and the text in the README.

Yes, I'll add link on Gogs README to LDAP README.

**Comment by Unknwon** [comment]
@SergioBenitez another note:

This PR will not be included in the next release(v0.6.5) which will be released in one day or two, because people need time to response on the issues that has been claimed to be fixed.

Hope you can understand! :blush:

**Comment by ArKam** [comment]
Hi, I'm the requester for the #1145 issue and I can confirm that your patch is everything I was looking for ! Awesome and well executed job, your readme is wonderful and really understandable by novices ! Thanks for the share to the community !

**Comment by Unknwon** [comment]
@SergioBenitez FYI, documentation has been updated: http://gogs.io/docs/features/authentication.html

**Comment by SergioBenitez** [comment]
Awesome, thanks @Unknwon. I noticed a few issues with the style in the README. I've submitted PR #1492 which fixes them.

**Comment by Unknwon** [comment]
@SergioBenitez I have updated gogs.io as well. :100:

**Comment by dolanor** [comment]
Just to thank @SergioBenitez . It works for me. :100:

**Pull request merged**
