### PR TITLE
Check if file is a symlink with web editor

### PR DESCRIPTION
**Pull request by gronke**
Prevents symlinks from being edited with the Web UI.

depends on https://github.com/gogits/git-module/pull/20

### CODE REVIEW

**Comment by LefsFlarey** [comment]
So, still dead?

**Comment by gronke** [comment]
Yeah, it needs https://github.com/gogits/git-module/pull/20 to be merged first.

**Comment by richmahn** [comment]
Glad to see this improvement to the web editor. Hopefully will get into master soon.

**Comment by LefsFlarey** [comment]
There shouldn't be a symlink in the repo directory, no?

**Comment by rbukovansky** [comment]
@LefsFlarey There can be symlinks in your repo and git can handle them well. See below. Symlinks have file mode 120000.

```
[rbukovansky@rb-fedora TestSymLinks]$ git diff --cached
diff --git a/symlinktest.txt b/symlinktest.txt
new file mode 120000
index 0000000..541cb64
--- /dev/null
+++ b/symlinktest.txt
@@ -0,0 +1 @@
+test.txt
\ No newline at end of file
diff --git a/test.txt b/test.txt
new file mode 100644
index 0000000..345e6ae
--- /dev/null
+++ b/test.txt
@@ -0,0 +1 @@
+Test
```

**Comment by Unknwon** [comment]
Thanks!

**Comment by gronke** [comment]
... merged right before 33c3 😼

**Pull request merged**
