### PR TITLE
GitHub-API compliance

### LINKED ISSUE #3729: Incompatible Issues API
- Gogs version (or commit ref): 0.9.99.0915
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
## Description

The current implementation for Issues API isn't compatable with GitHubs API. I'm proposing that this is fixed.
Reasons being:
- Docs states that Gogs aims to be compatible.
- Ability to use existing libs for talking to Gogs
- External services can support Gogs "for free" by having support for GitHub (which most do already)
#### Data-format

gogs:

``` json
{
  "id": 1,
  "name": "foobar",
  "color": "#bada55"
}
```

GitHub:

``` json
{
  "name": "foobar",
  "color": "bada55",
  "url": "https://api.github.com/repos/foo/bar/labels/foobar"
}
```
#### Fetching by `:id` instead of `:name`

Gogs: `/repos/:owner/:repo:/labels/:id`
GitHub: `/repos/:owner/:repo/labels/:name`

I'll add more things here as they appear

### PR DESCRIPTION
**Pull request by bkcsoft**
Fixes a couple of issues with the Gogs API.

Also adds the undocumented endpoint `/repositories/:id` (which is used by Octokit)

Closes #3729

### CODE REVIEW

**Comment by Unknwon** [comment]
We have conflicts here, are you willing to fix?

**Comment by bkcsoft** [comment]
@unknwon Done, and I renamed the function to align with the conflicing change :)

**Comment by Unknwon** [comment]
Thanks! Any idea why CI both are failing?

**Comment by Unknwon** [comment]
Thanks for the update, but code isn't seem compiling...

**Comment by Unknwon** [comment]
Closed by https://github.com/gogits/gogs/pull/4549.

**Pull request closed without merging**
