### PR TITLE
Fix for #3401 - Links of pull request comment email should use pulls URL

### PR DESCRIPTION
**Pull request by lstahlman**
See discussion on #3401

### CODE REVIEW

**Comment by lstahlman** [comment]
I signed the CLA before submitting the PR, but the CLA check says otherwise. When I click details, it confirms I have indeed signed it.

**Comment by Unknwon** [comment]
Never mind, this CLA service looks completely not working.

**Comment by Unknwon** [comment]
Thanks!

**Comment by Unknwon** [comment]
PS: I think CLA is not working because somehow you commited with Gogs(?), and that's not a valid user... just be careful with future commits.

**Comment by lstahlman** [comment]
Yeah, the author on the commit was correct but committer was not. I updated my config, so future commits should show the correct info.

**Pull request merged**
