### PR TITLE
Bug fix for query protected branches

### LINKED ISSUE #5053: Once branch was protected "Lock" icon will never be removed
- Gogs version (or commit ref): 0.11.34.1122
- Git version: 2.16.1
- Operating system: Windows
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant

Once a branch is protected by "Settings/Branches/Protect this branch" and later option is disabled again, the "Lock" icon within the branch overview list will never be removed again:

clipboard01

### PR DESCRIPTION
**Pull request by xwjdsh**
Signed-off-by: Wendell Sun <iwendellsun@gmail.com>

Fixes #5053

### CODE REVIEW

**Comment by bclermont** [comment]
this project is dead, stop wasting your time.
go to https://github.com/go-gitea/gitea/

**Comment by Unknwon** [comment]
Thank you!

**Comment by dr0p** [comment]
@Unknwon btw this change breaks SQLite db backend. Not sure about other db engines
https://github.com/gogits/gogs/commit/e4f187cd3d7e7cbc69b1bdf9ec58b4191c67aa7d#diff-c1dfde40ee07e932fca485f7fa98722bR255

In `and protected=true` `true` is considered as a column name, not a boolean.. sql standard does not have boolean so this should be protected=1 or something similar.

**Comment by Unknwon** [comment]
@dr0p good catch! Should be fixed by now.

**Comment by xwjdsh** [comment]
@dr0p @Unknwon I'm sorry for this.

**Comment by Unknwon** [comment]
@xwjdsh no worries, this an not-well-known XORM trick. :wink:

**Pull request merged**
