### PR TITLE
To add spanish translation to home template

### PR DESCRIPTION
**Pull request by xxxtonixxx**
Saludos! :+1:

### CODE REVIEW

**Comment by exmex** [comment]
F�c

uhm.. is that normal?

**Comment by xxxtonixxx** [comment]
It's so strange... I don't know but [in file](https://github.com/xxxtonixxx/gogs/blob/develop/templates/home.tmpl#L134) is okay, where it's bad is in the commit :-\

**Comment by exmex** [comment]
I don't think he'll merge this.. All the other languages are problematic in your file.

(Chinese):
```
ä¸€ä¸ªå»‰ä»·çš„æ ‘èŽ“æ´¾çš„é…ç½®è¶³ä»¥æ»¡è¶³ Gogs çš„æœ€ä½Žç³»ç»Ÿç¡¬ä»¶è¦æ±‚ã€‚æœ€å¤§ç¨‹åº¦ä¸ŠèŠ‚çœæ‚¨çš„æœåŠ¡å™¨èµ„æºï¼
```

**Comment by xxxtonixxx** [comment]
I'm going to see what is happened... I close it and I'll re-merge again, good catch! And sorry! :+1:

**Pull request closed without merging**
