### PR TITLE
Icon redesign

### PR DESCRIPTION
**Pull request by egonelbre**
Icon redesign with .svg.

### CODE REVIEW

**Comment by Unknwon** [comment]
This is awesome, thank you very much!

**Comment by Unknwon** [comment]
I'm going to update all documents.

**Comment by Unknwon** [comment]
All places should be updated now. Thanks again!

**Comment by jorgesumle** [comment]
Great work @egonelbre! @Unknwon, you should also update the screenshots in https://gogs.io/

**Comment by Unknwon** [comment]
@jorgesumle will do in next release :D

**Comment by jxsl13** [comment]
Old one was better :c

**Comment by egonelbre** [comment]
@jxsl13 any particular reason you don't like the new version?

**Comment by jxsl13** [comment]
The old one was unique, cute and appealing and you would directly know what it means, especially because of the go language mascot. You could say, it is a "unique selling point", the new one in comparison is just plain, nothing special, it could be the logo of anything, but not this project.

**Comment by egonelbre** [comment]
@jsxl13 Yeah, I agree with the cuteness part. The previous was not legible at smaller sizes, which is why I decided to go with a simpler design. Sure, I agree that there might be designs that I haven't considered that would be a better fit. I'll think about it, maybe I'll have some other better ideas.

**Comment by Unknwon** [comment]
See my response at [forum](https://discuss.gogs.io/t/discussion-what-does-the-community-think-about-the-new-logo/908/2?u=unknwon).

**Pull request merged**
