### PR TITLE
Collaboration

### PR DESCRIPTION
**Pull request by phsmit**
This PR introduces a new Collaboration struct which is a direct relation between a repository and a non-organization user. Introducing this table will make it much easier to refactor the access table

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR! Have classes today, will review soon.

**Comment by Unknwon** [comment]
I would like to review later PRs since this one introduce database migration(if I remember right), hope you don't mind :satisfied:

**Comment by phsmit** [comment]
No problem. One thing is that the next one (access refactoring) builds on this pr, so if big changes are needed that would be good to be done earlier

**Comment by Unknwon** [comment]
Thanks for the tip, I'll keep in mind!

**Comment by phsmit** [comment]
I made #925 now to the access branch

**Pull request closed without merging**
