### PR TITLE
[WIP] Openid support

### PR DESCRIPTION
**Pull request by strk**
this is really just a stub, adding here in case others want to help

### CODE REVIEW

**Comment by rawlingsj** [comment]
This would be a great feature.  I'm not sure I'm in a position to help but I can try, perhaps with a bit of testing when the time comes.  We use gogs on the [fabric8](https://fabric8.io/) project which runs on Kubernetes.  We're looking at authentication using OpenID with Keycloak so if any of that is interesting let me know and I can try to help.

**Comment by strk** [comment]
At this stage the help needed is with macaron and interaction design.
The code in the branch should let you add an "OpenID" authentication
method and then would take a Username containing "://" as an OpenID
url, and try to verify you against that (but won't create a local user
yet, just print - in the logs - whether or not you're verified).

**Comment by strk** [comment]
Oh, you also need to enter a password but is not used, just type
in a random character (that's where I need help with Macaron)

**Comment by Unknwon** [comment]
Is this still in development?

**Comment by strk** [comment]
Yes but the new development is based on Gitea. Feel free to close
this one unless you find something useful.

**Comment by Unknwon** [comment]
Thanks for clarifying!

**Pull request closed without merging**
