### PR TITLE
Enable Automated builds for rpi

### LINKED ISSUE #4180: Dockerfile and docker hub images for the Raspberry Pi are 5 months old
As said above, the images in [this docker hub repo](https://hub.docker.com/r/gogs/gogs-rpi/) are quite old. I've tried to `docker build` manually, too. `Dockerfile.rpi` seems not up to date:

- the parent image is quite old. There are new Alpine 3.5 based images now (such as [this](https://hub.docker.com/r/resin/raspberrypi2-alpine/));
- it does not `RUN` `build-go.sh` nor `finalize.sh`;
- from `master`, `RUN` `build.sh` fails at line 16 (`cd ${GOPATH}/src/github.com/gogits/gogs`).

Hope the information above is helpful.

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
With this commit you will be able to use the Docker Hub to Automate the builds for RPI ( ARMv7 ).

As a proof, you may take a look at https://hub.docker.com/r/julianxhokaxhiu/gogs/builds/

Fixes #4180

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks for the PR!

I'm not very sure about the change, would this patch affect non-dockerhub build?

**Comment by julianxhokaxhiu** [comment]
It will just work fine on any x86-64 platforms. Didn't test on the native archs, although I'm a fan of using the Hub for the dirty work, and leave people use it directly from there.

**Comment by Unknwon** [comment]
Maybe just create a new dockerfile specifically for DockerHub?

**Comment by julianxhokaxhiu** [comment]
All right, I'll do so later :)

**Comment by julianxhokaxhiu** [comment]
@Unknwon sorry for the many commits, but now it's done :) Fully separated. A build is in progress on my hub, to test it everything is fine. Feel free to take a look at it: https://hub.docker.com/r/julianxhokaxhiu/gogs/builds/

Sorry also about the long delay.

**Comment by Unknwon** [comment]
Thank you!

**Pull request merged**
