### PR TITLE
Avoid reading the whole request body in memory on push

### LINKED ISSUE #636: Large repo push http  : consumption of ram
I tried to push a large repository via http. Everything goes well until the transfer is finished eating ram becomes important (Gogs). It's a shame Gogs is so light yet in other cases. To see if this is not a technical limitation caused by the protocol, but I think it is possible to optimize.

### PR DESCRIPTION
**Pull request by strk**
Fixes #636
Deprecates #3162

@bkcsoft, @Unknwon review welcome

### CODE REVIEW

**Comment by strk** [comment]
Ok this doesn't work either:
```
[Macaron] PANIC: runtime error: slice bounds out of range
/usr/lib/go-1.6/src/runtime/panic.go:426 (0x42dc09)
        gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/lib/go-1.6/src/runtime/panic.go:21 (0x42c139)
        panicslice: panic(sliceError)
```

Maybe a ReadClose cannot be used here

**Comment by strk** [comment]
NOTE: despite the panic, pushes succeed (could be a panic triggered by the "Close" part of ReadCloser)

**Comment by bkcsoft** [comment]
I've looked into this one previously and it's a bit more difficult than that. We have to move some code into post-recieve-hook which means a large refactor...

**Comment by strk** [comment]
will close, not knowing what I'm doing anyway :)

**Pull request closed without merging**
