### PR TITLE
Update German translations

### PR DESCRIPTION
**Pull request by mikehaertl**
Please, make sure you are targeting the `develop` branch!

More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

### CODE REVIEW

**Comment by mikehaertl** [comment]
@Unknwon I'm sorry, I've spent a couple of hours to improve the German translation - it is really a mess right now. But then I've found that you don't accept pull requests for locale files :(((.

Any suggestions what to do? I hope, all my work was for nothing now.

**Comment by Unknwon** [comment]
Thanks your PR!

However, https://github.com/gogits/gogs/wiki/Contributing-Code#those-we-do-not-accept

**Comment by mikehaertl** [comment]
@Unknwon I know, but to me it seems obvious that the current system with crowdin does not work! The german translation is of very low quality. For example it's very inconsistent even in the salutation of the user or in translation of "issue". There's much more wrong.

Is there no way to somehow get my contribution merged?

**Comment by Unknwon** [comment]
Everyone thinks their translation is the best, as I don't know Germen at all, I can't do that just because you ask. I'm sorry.

**Comment by mikehaertl** [comment]
@Unknwon I understand that. I don't expect this to be merged without some discussion. But I think every German will agree that it's not acceptable to mix the two possible translations for "you" in German (Du/Sie). It's either always "Du" or always "Sie". Right now it's a wild mix of both.

Another thing is the inconsistens translation of terms like "Issue", "Mirror", etc. They should always use the same translation. That's also not the case. 

My suggestion here is an attempt to make this consistens all over the application. I think crowdin is not really the best tool to achieve a good translation. There should be one person in charge and maybe a catalog of common terms.

**Comment by Unknwon** [comment]
I'll see what I can do.

**Comment by Unknwon** [comment]
OK, I uploaded results to Crowdin, but under my name (with latest updated time), you can go https://crowdin.com/translate/gogs/1/enus-de to vote or just mention me on comment.

**Comment by mikehaertl** [comment]
Hmm, ok. At least something. Still a lot of work. But thanks!

**Comment by Unknwon** [comment]
It's a good lesson about what could happen if you don't read the docs before doing something, :D

**Comment by mikehaertl** [comment]
Yeah, sorry. I was so sure, that a simple PR is all I need. Another question: I see many phrases on crowdin with many upvotes. For example the translation for "Mirror". Someone translated it as "Spiegel", which sounds weird. The most votes are for "Mirror" (which is fine). So why is it still "Spiegel" in the locale file? Or how do you sync between crowdin and this repo?

**Comment by Unknwon** [comment]
@mikehaertl locale files in main repo is not up-to-date, that's why we ask you to do on Crowdin, I merge to main repo constantly.

**Comment by mikehaertl** [comment]
@Unknwon I'm sorry, I don't understand. Why is it not up to date, if you merge constantly?

**Comment by Unknwon** [comment]
I don't merge for every single change, but every week.

**Comment by mikehaertl** [comment]
@Unknwon Sorry, for bothering so much. But I still see many wrong translations, even if they have correct translations with many votes on crowin. For example:
https://github.com/gogits/gogs/blob/develop/conf/locale/locale_de-DE.ini#L790

The better German suggestion "Team-Repositories" has 4 upvotes, the bad "Team-Repositorys" has -1 votes. Both were proposed over a year ago. So why is the latter still in the main repo?

**Comment by Unknwon** [comment]
@mikehaertl because they did not get approved before last merge.

**Comment by mikehaertl** [comment]
@Unknwon Ok, final question: When will this approval happen or who's responsible for this? If this process is documented somewhere, then please forgive me and just point me there.

BTW I forgot to mention that I **love** what I see from gogs so far!! :) It's looks so much better in many regards than this nasty resource hog §$"#!..lab stuff. It even motivated me to immediately contribute some improvements for localization. So thanks, for all your hard work and keep it up!

**Comment by Unknwon** [comment]
> @Unknwon Ok, final question: When will this approval happen or who's responsible for this? If this process is documented somewhere, then please forgive me and just point me there.

I have mentioned, you take votes or mention on the comment.

**Comment by mikehaertl** [comment]
@Unknwon But highest votes are not always used?  See above.

**Comment by Unknwon** [comment]
I don't know which you are talking without Crowdin link. 

No activity recently, I could miss that one.

**Comment by mikehaertl** [comment]
@Unknwon See here: https://crowdin.com/translate/gogs/1/enus-de#379

I think there are many more like this.

**Comment by Unknwon** [comment]
Same rule: you take votes or mention me on the comment. I'll check on them.

**Comment by mikehaertl** [comment]
@Unknwon Hmm, Ok, I will continue to vote. But you already seem to have missed at least 3 votes on this one: It's +3:-2 votes. Still the one with -2 is approved. Maybe I still don't get it. Sorry.

**Pull request closed without merging**
