### PR TITLE
Ipython notebook support separate libraries

### PR DESCRIPTION
**Pull request by prinsherbert**
See https://github.com/gogits/gogs/pull/4067

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks. Have you resync with latest `develop` code? Because I see many deletions are newly added in Gogs codebase.

**Comment by Unknwon** [comment]
Hmm, after rebased from `develop`, I think you might need recommit these two commits so critical changes are combined and able to review.

**Comment by prinsherbert** [comment]
It should be up to date with the newest develop commit.

Most of those deletes are in `gogs.css`, which my lessc did, it created a slightly different css at some lines, I have no idea why, I simply used `make less`.

**Comment by Unknwon** [comment]
Many deletions in `.less` are newly added as well...

**Comment by prinsherbert** [comment]
Yes, and they are, right?

**Comment by Unknwon** [comment]
No,

For example:

- Deleted: https://github.com/gogits/gogs/pull/4068/commits/7cf86c5fc52521d1304c83e35dbc2a01a907f471#diff-4c18d74f0d0687b8503915779673f3ebL254
- Added: https://github.com/gogits/gogs/blob/master/public/less/_repository.less#L254

**Pull request closed without merging**
