### PR TITLE
#4145 simple docker alpine 3.5 go 1.8

### PR DESCRIPTION
**Pull request by yaourt**
Provide an updated Dockerfile where Gogs is build with Go 1.8
In order to have an up to date Docker image based on alpine 3.5
  and having Gogs built with Go 1.8

Refs: [ #4145 ]

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks, tested locally seems working.

**Comment by Unknwon** [comment]
Any clue this image size is increased by 10MB? 
image

**Comment by yaourt** [comment]
Oh, this is strange ...
Locally, I've the same things:

```
$ docker images 
REPOSITORY                                          TAG                 IMAGE ID            CREATED             SIZE
mygogs                                              1.8                 5da443495d08        21 minutes ago      105 MB
gogs/gogs                                           0.9.141             0efbc5cc2550        7 days ago          90 MB
```

But from the docker images themselves, I don't see anything wrong : 

From the "official" Gogs 0.9.141 image:
 ```
$ docker run -t -i gogs/gogs:0.9.141 /bin/sh
/app/gogs # du -sh /*
55.5M	/app
2.5M	/bin
28.0K	/data
0	/dev
1.7M	/etc
4.0K	/home
4.3M	/lib
0	/linuxrc
16.0K	/media
4.0K	/mnt
0	/proc
8.0K	/root
4.0K	/run
340.0K	/sbin
0	/sys
4.0K	/tmp
33.9M	/usr
68.0K	/var
```


From the new image :
```
docker run -t -i mygogs:1.8 /bin/sh
/app/gogs/build # du -sh /*
46.6M	/app
2.6M	/bin
388.0K	/core
28.0K	/data
0	/dev
1.9M	/etc
4.0K	/home
3.7M	/lib
16.0K	/media
4.0K	/mnt
0	/proc
12.0K	/root
4.0K	/run
320.0K	/sbin
4.0K	/srv
0	/sys
4.0K	/tmp
35.8M	/usr
76.0K	/var
```

**Comment by Unknwon** [comment]
Might Go 1.8 just generates larger binary...

**Comment by yaourt** [comment]
I don't think so ...

The new gogs binary is 29MB while the older one is 32 MB.

I think it is related to Docker image layers but I don't see from where it comes.

**Comment by Unknwon** [comment]
Got no idea... anyway, right now seems good, removed 1MB unused font files

**Comment by yaourt** [comment]
I think it is coming from the 3 scripts line : build-go.sh && build.sh && finalize.sh.
But I don't know why.

A docker history --human=false --no-trunc on the official 0.9.141 version is giving this :
```
IMAGE                                                                     CREATED                     CREATED BY                                                                                                                                SIZE                COMMENT
sha256:0efbc5cc2550ec758b91415c68a3cf5fda9e650eaaeb13a2aaaba293fd489b0a   2017-02-11T10:15:54+01:00   /bin/sh -c #(nop)  CMD ["/bin/s6-svscan" "/app/gogs/docker/s6/"]                                                                          0                   
<missing>                                                                 2017-02-11T10:15:53+01:00   /bin/sh -c #(nop)  ENTRYPOINT ["docker/start.sh"]                                                                                         0                   
<missing>                                                                 2017-02-11T10:15:52+01:00   /bin/sh -c #(nop)  EXPOSE 22/tcp 3000/tcp                                                                                                 0                   
<missing>                                                                 2017-02-11T10:15:50+01:00   /bin/sh -c #(nop)  VOLUME [/data]                                                                                                         0                   
<missing>                                                                 2017-02-11T10:15:49+01:00   /bin/sh -c #(nop) COPY file:f8eb304cc138536db36c812949df7e3bd3b4894199fc3b71688a1c38f63700f5 in /etc/nsswitch.conf                        263                 
<missing>                                                                 2017-02-11T10:15:48+01:00   /bin/sh -c ./docker/build.sh                                                                                                              33981028            
<missing>                                                                 2017-02-11T10:12:10+01:00   /bin/sh -c #(nop)  WORKDIR /app/gogs/                                                                                                     0                   
<missing>                                                                 2017-02-11T10:12:09+01:00   /bin/sh -c #(nop) COPY dir:4793a82e7c9509f4aeac4ed7e5f7040ef761f8bce19d9d9a37f28960f6d18248 in /app/gogs/                                 18994414            
<missing>                                                                 2017-02-11T10:12:05+01:00   /bin/sh -c #(nop)  ENV GOGS_CUSTOM=/data/gogs                                                                                             0                   
<missing>                                                                 2017-02-11T10:12:05+01:00   /bin/sh -c chmod +x /usr/sbin/gosu  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat tzdata   30375540            
<missing>                                                                 2017-02-11T10:11:58+01:00   /bin/sh -c #(nop) ADD tarsum.v1+sha256:541927699b49bc39613cf73183eb6184ae901d3d5f3bca8f8364e9ce62f31715 in /usr/sbin/gosu                 1804608             
<missing>                                                                 2017-02-11T10:11:58+01:00   /bin/sh -c #(nop)  MAINTAINER jp@roemer.im                                                                                                0                   
<missing>                                                                 2016-12-27T19:17:01+01:00   /bin/sh -c #(nop) ADD file:62421fd56c1160b96b28fc8320ae4332f8578329ea675d45e7c54a4d161d6d89 in /                                          4804991             
```

While on the new image it is giving this :
```
IMAGE                                                                     CREATED                     CREATED BY                                                                                                                                SIZE                COMMENT
sha256:5da443495d08cf6526b5728358712de934109ef482af10555eee2ace0be4539d   2017-02-19T02:43:03+01:00   /bin/sh -c #(nop)  CMD ["/bin/s6-svscan" "/app/gogs/docker/s6/"]                                                                          0                   
sha256:3860abb96da35412232584f8223c6bde00a30bb1e78afa834bbba2e7bc923377   2017-02-19T02:43:03+01:00   /bin/sh -c #(nop)  ENTRYPOINT ["/app/gogs/docker/start.sh"]                                                                               0                   
sha256:a933f3af2424db59cce7ca795620851a92f9f08047a30acc55c8bef8ca190cd7   2017-02-19T02:43:03+01:00   /bin/sh -c #(nop)  EXPOSE 22/tcp 3000/tcp                                                                                                 0                   
sha256:8a76d236eb6e471b731fb0906a3746a2b9ec1ead71e8acc38e68d9ee7da0517e   2017-02-19T02:43:02+01:00   /bin/sh -c #(nop)  VOLUME [/data]                                                                                                         0                   
sha256:c2fdd042bd94ff863488f99b91f313a3c372bf992e99a863bebe807a5b14c274   2017-02-19T02:43:02+01:00   /bin/sh -c #(nop) COPY file:8b59d2e553cdf79781ce7b9c0393f4040c500cf33e2bc21d1710b66d44584a32 in /etc/nsswitch.conf                        263                 
sha256:f542cb2cc650d01afe64349a278a835cbab1d20828cf164bdca9241204dcfa00   2017-02-19T02:43:02+01:00   /bin/sh -c ./docker/build-go.sh     && ./docker/build.sh     && ./docker/finalize.sh                                                      46393394            
sha256:456e55dcd4239004e9035756d8d08941d8d24d62d19baab2674417a32255ebff   2017-02-19T02:37:14+01:00   /bin/sh -c #(nop) WORKDIR /app/gogs/build                                                                                                 0                   
sha256:9feb356f4865ded14c4d340bc78cc8b96b051a105ec426cbec8739f0fae56458   2017-02-19T02:37:14+01:00   /bin/sh -c #(nop) COPY dir:fdda4c0e062ecee16d821c46f7e3a962199d7863412738f95ad7cd3a0b1d6ceb in /app/gogs/build                            20353009            
sha256:f6391b09c036987369272ae46ee9738d613f172ec43ea6feb3e0c2fe7cfbf625   2017-02-19T02:37:13+01:00   /bin/sh -c #(nop)  ENV GOGS_CUSTOM=/data/gogs                                                                                             0                   
sha256:2b35495e92acf5c366330e40860f1195191dec7a7456ff36aea9ce40fd3906ec   2017-02-19T02:37:12+01:00   /bin/sh -c chmod +x /usr/sbin/gosu  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat tzdata   32760947            
sha256:6d1452361800fb6f14f53144bc0c45cd0b3d2c7f29d0fb823cb4d36f7a258aa3   2017-02-19T02:36:58+01:00   /bin/sh -c #(nop) ADD tarsum.v1+sha256:541927699b49bc39613cf73183eb6184ae901d3d5f3bca8f8364e9ce62f31715 in /usr/sbin/gosu                 1804608             
sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd   2016-12-27T19:17:25+01:00   /bin/sh -c #(nop) ADD file:92ab746eb22dd3ed2b87469c719adf3c1bed7302653bbd76baafd7cfd95e911e in /                                          3983615             
```

**Comment by yaourt** [comment]
I just had a look on the result of my previous PR, the result is the following :
```
IMAGE                                                                     CREATED                     CREATED BY                                                                                                                                SIZE                COMMENT
sha256:6ade165156fb73bdd76cf41bdcd5b8232a1b08a8206684d125bb05aeca5d3266   2017-02-19T03:33:03+01:00   /bin/sh -c set -ex  && sh /app/gogs/docker/build-go.sh  && sh /app/gogs/docker/build.sh                                                   46419524            
sha256:2d85468c4e9bd9ce1ecabdda0db1feaadd271c13fde8d98db41b4bb880958377   2017-02-19T03:29:53+01:00   /bin/sh -c #(nop) COPY dir:a9901f0d51a8650c0d0c1bc536865e6788c7b14f403bfdd174107f15af809cac in /app/gogs/docker                           11787               
sha256:92df261cc34951d7df85ba7f38e4e80ac1e536565a87ad0fc8182e798860b7ea   2017-02-19T03:28:56+01:00   /bin/sh -c #(nop)  CMD ["/bin/s6-svscan" "/app/gogs/docker/s6/"]                                                                          0                   
sha256:db2df1aaabc7626d4beac4e6fe92375cd3f8214787917277220f275cc92d8e9d   2017-02-19T03:28:56+01:00   /bin/sh -c #(nop)  ENTRYPOINT ["/app/gogs/docker/start.sh"]                                                                               0                   
sha256:d7c5d4b6c8e05fe3e6243545c8d805a52a62f0cb41d79e81bbae2fadc4ce8bbe   2017-02-19T03:28:56+01:00   /bin/sh -c #(nop)  EXPOSE 22/tcp 3000/tcp                                                                                                 0                   
sha256:9d19da8c66819f7c34ad1276c528d720353b0caa7abc7be0b6be2770b9e08d13   2017-02-19T03:28:56+01:00   /bin/sh -c #(nop)  VOLUME [/data]                                                                                                         0                   
sha256:48a6169b3502650a276a3021f0cb1ecf20b24c66069093c389305d6b789bc9d9   2017-02-19T03:28:55+01:00   /bin/sh -c #(nop) COPY file:8b59d2e553cdf79781ce7b9c0393f4040c500cf33e2bc21d1710b66d44584a32 in /etc/nsswitch.conf                        263                 
sha256:6faad6f23910a2fee62607ba2867423ae76c70b6d1b9fcde833476ebb737ef97   2017-02-19T03:28:55+01:00   /bin/sh -c #(nop)  ENV GOGS_CUSTOM=/data/gogs                                                                                             0                   
sha256:fab2478d6bf50cd60146f10d97eadf2bee41c34e53c169185253f943bf7b394b   2017-02-19T03:28:55+01:00   /bin/sh -c chmod +x /usr/sbin/gosu  && apk --no-cache --no-progress add ca-certificates bash git linux-pam s6 curl openssh socat tzdata   32760947            
sha256:fc2e832af75d2b5e144239da92cd9628eef7c85f110c9af049d60da2fdee2a8b   2017-02-19T03:28:41+01:00   /bin/sh -c #(nop) ADD tarsum.v1+sha256:541927699b49bc39613cf73183eb6184ae901d3d5f3bca8f8364e9ce62f31715 in /usr/sbin/gosu                 1804608             
sha256:bb1ef3ff0460c393f1853f621ec6b79f0c9312d77941901109464d6bf6345132   2017-02-19T03:28:38+01:00   /bin/sh -c #(nop)  ENV GOGS_VERSION=develop                                                                                               0                   
sha256:1ad3ae10fea5b31c861992c9d1b4b7d2f3c357a1ef0d3e30810b99663cb921ca   2017-02-19T03:28:38+01:00   /bin/sh -c #(nop)  ENV GOLANG_SRC_SHA256=406865f587b44be7092f206d73fc1de252600b79b3cacc587b74b5ef5c623596                                 0                   
sha256:73bb2f263dc6a69aa2b70ea2237fa1dbe80ac9c7ba3cc65a1af6117a62cb3966   2017-02-19T03:28:37+01:00   /bin/sh -c #(nop)  ENV GOLANG_SRC_URL=https://golang.org/dl/go1.8.src.tar.gz                                                              0                   
sha256:a18b83fcada201265d2ebd7f426e0b1ea4821d89375f77fa08c25282a87437f8   2017-02-19T03:28:37+01:00   /bin/sh -c #(nop)  ENV GOLANG_VERSION=1.8                                                                                                 0                   
sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd   2016-12-27T19:17:25+01:00   /bin/sh -c #(nop) ADD file:92ab746eb22dd3ed2b87469c719adf3c1bed7302653bbd76baafd7cfd95e911e in /                                          3983615             
```

**Comment by Unknwon** [comment]
Thanks for the debugging... but what do these output mean?

**Comment by yaourt** [comment]
For each docker command, each line from the Dockerfile, you have a Docker image layer.

This `docker history` command gives the size of each of those layers (see the SIZE column on the right).
The sum of those layers size is giving the final image size.

IMHO it is a good way to track from where the image _fat_ is coming from ...

**Comment by Unknwon** [comment]
I see. Nothing seems wrong to me...

**Pull request merged**
