### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by OhDaeto**
Slightly corrected translation

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks. Next time, please read the README.

1. Do it on Crowdin.
2. PR to `develop`.

**Comment by OhDaeto** [comment]
I'll know

**Comment by Unknwon** [comment]
:wink:

**Comment by OhDaeto** [comment]
I made update on Crowdin

**Comment by Unknwon** [comment]
Approved all.

**Pull request merged**
