### PR TITLE
Added reverse proxy auth to HTTP push/pull

### PR DESCRIPTION
**Pull request by joe-french**
Added check of reverse proxy authentication options to allow for
pushing / pulling of repositories using reverse proxy authentication.

This implementation likely isn't the best, as it seems like there needs to
be some single sign on method that aligns with the code in
modules/auth/auth.go.

### CODE REVIEW

**Comment by joe-french** [comment]
I made this PR regarding the #2889 that I created, but it may resolve #2170, and the issue I was running into sounds a lot like #2692 .

**Comment by Zamicol** [comment]
Thanks @joe-french for your work.  

I compiled joe-french:develop and it didn't fix the issues from #2692.

**Comment by Unknwon** [comment]
Please solve the conflict...

**Comment by dl5rcw** [comment]
After getting gogs + reverse proxy (apache 2.4) to work, I enabled the auto create user function. Works fine with basic auth now. Starting to merge my svn, I ran into the clone/pull/push conflict. Seems like public repos can be clones, but not pull/push. 
This seems to be a real issue as all those related issues are mentioned here.

**Pull request closed without merging**
