### PR TITLE
New gitlab-like line naming style support in comments

### PR DESCRIPTION
**Pull request by makhov**
Make comments work with #970. 
Merge actual branches from #972.

### CODE REVIEW

**Comment by Unknwon** [comment]
Hmm... can't merge...

**Comment by Unknwon** [comment]
BTW... merge `dev` upon `access` or `comment` isn't a good move... please wait until I finish testing access branch code.

**Comment by makhov** [comment]
Uh, ok.

**Comment by Unknwon** [comment]
@makhov sorry about merge conflict.

**Pull request closed without merging**
