### PR TITLE
Added Units for repo, access and team. First step of three on #3027.

### PR DESCRIPTION
**Pull request by lunny**
For the first step of #3027, we added units for repository, access and team. And it's completely compatible with old repos. And there are no any changes on User's UI.

The second, we can change repo's settings page to let user to choose which units admin to want. Code, Issues,  Pulls, Commits, Releases, Wiki, Settings. So the repos' home page will dynamically show the units according the repo's settings.

The last step, we will change repo's access and team's access page to dynamically show the units according the user's access.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

But please keep `migration.go` in its own package... it's not a good thing to mix it with models as it could contain legacy code and `models` changes over time.

**Comment by lunny** [comment]
Hi, I have to move `migration.go` to models folder. Because `migration.go` will reference some struct (for this PR is `Access`, `Team`, `Repository` and `UnitType`) defined on `models` and `models` will reference `migrate`. It will result in recycle reference.

**Comment by Unknwon** [comment]
Make new independent copy of structs, there is no grantee the struct will remain the same in the future, therefore the migration would fail.

**Comment by lunny** [comment]
OKay. Another question, I think migrations could be execute before or after `xorm.Sync2`.  So I have changed the migrations. Do you have any idea about that?

**Comment by Unknwon** [comment]
What is the advantage doing migration before sync tables?

**Comment by lunny** [comment]
In fact, all of the before migration is exeuted before sync tables. In this case, we need set the default units to some fields after sync tables (added some units field on team, access,repository).

**Comment by Unknwon** [comment]
Hmm... I don't know what you mean..

**Comment by lunny** [comment]
See https://github.com/gogits/gogs/blob/master/models/models.go#L183
```Go
func NewEngine() (err error) {
	if err = SetEngine(); err != nil {
		return err
	}

	if err = migrations.Migrate(x); err != nil {
		return fmt.Errorf("migrate: %v", err)
	}

	if err = x.StoreEngine("InnoDB").Sync2(tables...); err != nil {
		return fmt.Errorf("sync database struct error: %v\n", err)
	}

	return nil
}
```
Migration will be executed before sync2.

**Comment by Unknwon** [comment]
Yes, but why is that?

**Comment by Unknwon** [comment]
OK... I got it. What is the problem right now?

**Comment by lunny** [comment]
I will move back migrations to sub folder and PR again.

**Comment by lunny** [comment]
I sent a new PR #3336 since the codes changed a lot. Please code review that. @Unknwon I will close this PR.

**Pull request closed without merging**
