### PR TITLE
Rewrite/simplify gogs serve

### PR DESCRIPTION
**Pull request by phsmit**
Serve will not leak anymore the existence of repositories when the user does not have access to them. It will however give better feedback in other cases.

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi @phsmit , would you like to resolve the conflict?

**Comment by phsmit** [comment]
Conflict resolved

**Comment by Unknwon** [comment]
Some critical issues, but I'll change it after PR, thanks again!

**Comment by Unknwon** [comment]
> Some critical issues

False alarm.

**Pull request merged**
