### PR TITLE
Update locale_pt-BR.ini

### PR DESCRIPTION
**Pull request by andreynering**
I made a pass. Some translations are still missing or could be enhanced.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

But please see http://gogs.io/docs/features/i18n#make-corrections :sweat_smile:

**Comment by andreynering** [comment]
Sorry, I should have read the contributing guide.

I am suggesting changes on Crowdin. Should I close this pull request?

**Comment by Unknwon** [comment]
Yes, you can close it.

BTW, what is your username on Crowdin, I can give you permission to approve/disapprove .

**Comment by andreynering** [comment]
The same as GitHub: andreynering

**Comment by Unknwon** [comment]
OK, done.

**Pull request closed without merging**
