### PR TITLE
Fix #4706: Issue mentions should also render with square brackets

### LINKED ISSUE #4706: Issue mentions should also render with square brackets
- Gogs version (or commit ref): 0.11.29
- Git version: 2.7.4
- Operating system: Ubuntu
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
    - https://try.gogs.io/cstroe/testrepo/pulls/4#issuecomment-1836
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

Pull Request https://github.com/gogits/gogs/pull/2992 added an alphanumeric style of issue mention like `ABC-123` to Gogs.  While the issue mention is detected when it is surrounded with parentheses `(ABC-123)`, it doesn't work with square brackets `[ABC-123]`.

A user requested this fix: https://github.com/gogits/gogs/pull/2992#issuecomment-323169834

### PR DESCRIPTION
**Pull request by cstroe**
Fixing issue #4706 

Issue mentions are now allowed between square brackets.

### CODE REVIEW

**Comment by mqudsi** [comment]
fwiw, looks good to me and working fine here.

**Comment by cstroe** [comment]
@Unknwon , how do we get this merged?

**Comment by Unknwon** [comment]
Sorry, forgot. Thanks!

**Comment by rokuu** [comment]
@Unknwon Not fixed 

screenshot from 2018-04-23 07-52-03

https://try.gogs.io/cstroe/testrepo/pulls/4

**Comment by Unknwon** [comment]
@cstroe do you have any ideas?...

**Comment by mqudsi** [comment]
The regex still has to be defined, this was a patch for `[PROJ-1234]` support.

**Comment by cstroe** [comment]
@Unknwon The issue is fixed.  The repository that is linked above didn't have the external issue tracker enabled.  This is what I did to enable it:

enable-numeric-issues

Now you can see that numeric references are rendered on comments, with and without square brackets:

test-reference

**Comment by cstroe** [comment]
I also tested with the internal issue tracker, and it works just as well.

**Pull request merged**
