### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by suhongrui**

### CODE REVIEW

**Comment by Unknwon** [comment]
We truly appreciate your work!

But,

1. I think we've said that we want to work on initial version all on our own. And we've started working on pull-request branch.
2. Please even with dev branch, current diff page really doesn't help any. :)

**Comment by Unknwon** [comment]
PS: we don't accept PR to master branch.

**Comment by bastiao** [comment]
if I installed from master it should already support the pull request feature?

**Comment by Unknwon** [comment]
@bastiao this PR is a joke, this account just tried to PR my WIP code to `master` which we declined of course.

**Pull request closed without merging**
