### PR TITLE
Update TRANSLATORS

### PR DESCRIPTION
**Pull request by alexyer**
Updated TRANSLATORS file

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi, somehow we got conflict, would you mind fix it?

**Comment by alexyer** [comment]
Sure

**Comment by Unknwon** [comment]
Oh, actually I can fix it online! Cool feature!

**Comment by Unknwon** [comment]
Thank you!

**Comment by alexyer** [comment]
You are welcome. Thanks for accepting the PR

**Pull request merged**
