### PR TITLE
Fix language names

### PR DESCRIPTION
**Pull request by sikmir**
This PR fixes the follow issues:

1. wrong language name: "Suomalainen" is incorrect name for Finnish language, should be "suomi".
2. wrong capitalization of language names: different languages have different conventions for capitalization.

### CODE REVIEW

**Comment by Fastidious** [comment]
This will not be accepted.

**Comment by sikmir** [comment]
@Fastidious Why? "Suomalainen" is totally wrong name for language.

**Comment by Fastidious** [comment]
Oh, I might have gotten confused, and be wrong, after all.

**Comment by Unknwon** [comment]
Thank you!

@Fastidious changes to `app.ini` can be modified via PR :wink:

**Pull request merged**
