### PR TITLE
Ipython notebook support

### PR DESCRIPTION
**Pull request by prinsherbert**
I added ipython notebook renderering, unfortunately I could not find any Go-libraries that do this, hence I implemented it via Javascript.

This would in part solve this issue https://github.com/gogits/gogs/issues/3715

Not completely, because I only created it for python notebooks, I have no Idea how it would and should work for julia, R and possibly other programming language notebooks

### CODE REVIEW

**Comment by prinsherbert** [comment]
Simple example ipython notebook:

ipynb-gogs

**Comment by Unknwon** [comment]
Thanks for the PR! And the preview looks incredibly good.

However, the change set is so huge, it is not easy for merging. Instead of merging, I may take this PR as a source when implement this feature when Gogs has plugin system, that's much easier to maintain.

**Comment by prinsherbert** [comment]
> Thanks for the PR! And the preview looks incredibly good.

Thank you! And thank you for your fast response. 

> However, the change set is so huge, it is not easy for merging. Instead of merging, I may take this PR as a source when implement this feature when Gogs has plugin system, that's much easier to maintain.

@Unknwon Some of the library-files might be superfluous, I simply downloaded the github-releases. Moreover, the changes should only be in the `public/plugins`-folders, which should not prove troublesome when merging.

Another, possibly less relevant note, I like to collaborate with notebooks in git, because they allow me to share results of scientific research with others easily (including plots and such) and help me document experiments. This feature in gogs would help me a great deal.

**Comment by Unknwon** [comment]
Thanks for the response!

To help review, would you mind put actual code and library dependency in separate commits?

**Comment by prinsherbert** [comment]
> To help review, would you mind put actual code and library dependency in separate commits?

Yes, here you are: https://github.com/gogits/gogs/pull/4068

**Comment by oroszl** [comment]
Hey @prinsherbert great effort! Can you discribe a bit more in detail how you do the notebook rendnering ?
Specifically are you using nbconvert ?

**Comment by prinsherbert** [comment]
@CarlosGtrz No, I use notebookjs, a javascript library which transforms the notebook json into HTML, then I created some CSS to style

**Pull request closed without merging**
