### PR TITLE
Enable Automated builds for aarch64 ( ARM64 ) platforms

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
With these commits you will be able to use the Docker Hub to Automate the builds for ARM64 platforms.

As a proof, you may take a look at https://hub.docker.com/r/julianxhokaxhiu/gogs/builds/ ( aarch64 tag )

Related to #4180

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi, hmm. It is good to have automated builds, but if I'm not missing anything, you use cross build which doesn't have SQLite3 support.

**Comment by julianxhokaxhiu** [comment]
At the current status I backported the Dockerfile using the concept you use to build on native platforms.

Can you please point me where is the sqlite3 missing?

**Comment by Unknwon** [comment]
Based on [Build with Tags](https://gogs.io/docs/installation/install_from_source#build-with-tags) and [Install from binary](https://gogs.io/docs/installation/install_from_binary), ARM binary should have tags `sqlite`, `pam` and `cert` applied/enabled when compile.

**Comment by cruz210** [comment]
Can you help enable builds

**Comment by julianxhokaxhiu** [comment]
I see, then I would need to do another PR for the other file too. Can you please merge this so I can open another PR and I patch both armv7 and aarch64 :)

**Comment by julianxhokaxhiu** [comment]
Actually analyzing both Dockerfile I see I'm using build scripts inside the `docker` directory.

Maybe this is something you can fix it on your own? As is nothing related to the dockerfiles themself. Or am I missing something?

**Pull request merged**
