### PR TITLE
Fixes security issue #3110

### PR DESCRIPTION
**Pull request by kinnarr**
Please, make sure you are targeting the `develop` branch!

More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

Fixes security issue #3110 by checking if sha token is empty and returning error in this case

### CODE REVIEW

**Comment by roblabla** [comment]
Eh, that's weird. Doesn't that mean that there is an empty AccessToken in the database ? I'm pretty sure that's not normal.

**Comment by kinnarr** [comment]
No. It's the way, how xorm queries the db. If there is no query (or an empty query, because sha is empty), it returns the first entry in the table.

**Comment by bkcsoft** [comment]
Looks good to me :+1:

**Comment by Unknwon** [comment]
Seems having conflict?

**Comment by kinnarr** [comment]
@Unknwon fixed

**Comment by Unknwon** [comment]
It would be even better to cleanup into 1 commit :D

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
