### PR TITLE
Remove SSH button when SSH it is disabled

### PR DESCRIPTION
**Pull request by gustavopaes**
#1453

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks! 

However Gogs actually uses less file to generate css files. 

I can do it for you tomorrow morning or you can update the PR. 😀

**Comment by gustavopaes** [comment]
Oh really? I didn't know that. I can update the PR, no problem.

**Comment by Unknwon** [comment]
In this case, it should be in somewhere public/ng/less/Gogs/repository.less

**Comment by gustavopaes** [comment]
yes, I found it. How can I compile less in go projects? I didn't see any Grunt or Gulp (common in nodejs projects)

**Comment by Unknwon** [comment]
There is a sh in scripts directory could be helpful. I personally use codekit.

**Pull request merged**
