### PR TITLE
Add LibreJS support

### PR DESCRIPTION
**Pull request by jorgesumle**
https://github.com/gogits/gogs/issues/4084 I've finished the librejs template file, but I need some help with routes. 

I'm not sure how do templates routes work and I don't want to make something wrong. I'm trying to make gogsbaseurl.com/librejs to contain the LibreJS page, but can make it work and I'm afraid to break something. Once that is done, I'll have no problem adding a link to the footer template. Could one active/experienced programmer in this project help me?

Sorry for my ignorance, I never programmed in Go and I'm having a hard time in understanding how the code works.

### CODE REVIEW

**Comment by Unknwon** [comment]
Does the URL has to be `gogsbaseurl.com/librejs`?

**Comment by jorgesumle** [comment]
No, it could be in gobaseurl.com/otherfolder/librejs or in another place, but it should always be in the gobaseurl.com website.

**Comment by Unknwon** [comment]
Hmm, if it's not a fixed path, how does LiberJS know where to find this page?

**Comment by jorgesumle** [comment]
In the [footer.tmpl](https://github.com/gogits/gogs/blob/master/templates/base/footer.tmpl) template, you must create a link pointing to that URL and also use `data-jslicense="1"`. I didn't do that yet, because first I want to make the URL to work.

    <a hidden href="/librejs" data-jslicense="1">JavaScript licenses</a>

**Comment by Unknwon** [comment]
I see. So for the HTML page you're trying to put, I think it is purely static and only for the purpose of LiberJS? 

Then we could put it under `public/assets/liberjs/liberjs.html`, and make it a self-contained HTML page. To access that page by **gobaseurl.com/assets/liberjs/liberjs.html**. Sounds good?

**Comment by strk** [comment]
@jorgesumle I love this PR: would you mind sending a similar one for https://github.com/go-gitea/gitea ?

**Comment by jorgesumle** [comment]
Done. Thanks for your help @Unknwon. I'll watch this repo and update the LibreJS table every time a new JavaScript library is updated or added.

Apart from the changes you suggested, I changed the link of the source file to the tar.gz file because I was told that that was the correct approach in the LibreJS mailing list: http://lists.gnu.org/archive/html/help-librejs/2017-02/msg00003.html.
bildschirmfoto vom 2017-02-07 22-09-04
bildschirmfoto vom 2017-02-07 22-09-37

**Comment by Unknwon** [comment]
Looks good!

> I'll watch this repo and update the LibreJS table every time a new JavaScript library is updated or added.

You might have some work soon regarding this PR: https://github.com/gogits/gogs/pull/4070 It's going to be merged with two new JS libs.

**Comment by jorgesumle** [comment]
> @jorgesumle I love this PR: would you mind sending a similar one for https://github.com/go-gitea/gitea ?
I don't think I have time right now. I would have to check its JavaScript files, install Gitea and test it. I made this contribution because I was a NotABug user and I use Gogs every day, but it's very tedious to make a pull request like this.
> You might have some work soon regarding this PR: #4070 It's going to be merged with two new JS libs.
No problem with that. :)

**Comment by Unknwon** [comment]
FYI, the #4070 is merged, it's good to merge that PR before this one so you only need to verify your work once at this point.

**Comment by jorgesumle** [comment]
OK, I added `/plugins/marked-0.3.6/marked.min.js` and `/plugins/notebookjs-0.2.6/notebook.min.js` from #4070 to the table of LibreJS. I used `git push -f` so that there is only one clean commit.

**Comment by Unknwon** [comment]
>I used git push -f so that there is only one clean commit.

Actually we don't need to do that anymore because GitHub allows squash commits while merging.

Another question, since we're now link the license page for each JS lib, do we need to keep the license file (e.g. https://github.com/gogits/gogs/tree/master/public/plugins/marked-0.3.6) in our codebase anymore?

**Comment by jorgesumle** [comment]
No. Here is an example from LibreJS documentation:
  ```
  <tr>
        <td><a href="all.min.js">all.min.js</a></td>
        <td>
            <a href="http://www.gnu.org/licenses/gpl-3.0.html"
                >GPL-3.0+</a>
            <br />
            <a href="http://www.apache.org/licenses/LICENSE-2.0"
                >Apache-2.0</a>
        </td>
        <td>
            <a href="gpl-script.js">gpl-script.js</a>
            <br />
            <a href="apache-script.js">apache-script.js</a>
        </td>
    </tr>
```
As you can see the license links are external. However, I chose to link to the license file directly because it's inside Gogs (/plugins/marked-0.3.6/LICENSE). There is an example of that also in the LibreJS documentation: 

> More information on JavaScript Web Labels is detailed here: https://www.gnu.org/software/librejs/free-your-javascript.html#step3 and here: https://www.gnu.org/licenses/javascript-labels.html.

**Comment by Unknwon** [comment]
Thanks for the explanation!

In fact I would like to delete license files of JS libs from Gogs codebase and point to its license in **liberjs.html** file.

I can do that after merge the PR, or if you would like to help a bit and do it within the PR.

**Comment by jorgesumle** [comment]
Can you please do that?

**Comment by Unknwon** [comment]
OK, I'll do it. Thanks again for the PR!

**Comment by Unknwon** [comment]
Just realized I keep typing **liberjs** where should be **librejs**... Anyway, it's now online on https://try.gogs.io/assets/librejs/librejs.html

**Comment by alexgleason** [comment]
Looks like a few scripts have been updated now but the Javascript licenses page no longer reflects that. I wonder if there's a way to automate this process during build? Gogs is broken in LibreJS.

**Comment by Unknwon** [comment]
Would love to see another PR to fix this... :trollface:

**Pull request merged**
