### PR TITLE
[WIP] Started to integrate DroneCI

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
As an addition I will add/update tasks within the Makefile. And maybe we should discuss the usage of `gox` for simplified cross compilation :)

**Comment by Unknwon** [comment]
If no CGO, the easiest way to cross compile is upgrade to Go 1.5

**Comment by tboerger** [comment]
But with sqlite support CGO should be enabled

**Comment by Unknwon** [comment]
Yes, so in CI, we can use gox, but the bootstrap time I think is quite long.

**Comment by vtolstov** [comment]
Does gogs support status api to allow drone notify gogs about successful build ?

**Comment by Unknwon** [comment]
Currently not support

**Comment by tboerger** [comment]
@vtolstov that's a totally different topic. This PR ist just for adding .drone.yml to gogs :)

**Comment by tboerger** [comment]
Waiting for the successful build but it looks promising. When everything works fine I will remove the WIP flag, @Unknwon needs to add the .drone.sec and change how the docker images are getting built.

With that change we will have autobuilt binaries/archives for windows, linux, mac, freebsd, openbsd and netbsd in all available architectures.

Maybe the build from source section of the docs need some update as well as I have updated the Makefile.

**Comment by tboerger** [comment]
Damn, still one issue with `make release`, it generates only binaries for openbsd/amd64, linux/amd64, darwin/amd64 and freebsd/amd64. Got to figure out why...

**Comment by Unknwon** [comment]
:+1:

**Comment by tboerger** [comment]
I think I will remove the gox stuff and will use the native go 1.5 crosscompile functionality.

**Comment by Unknwon** [comment]
@tboerger Haha, welcome back.

**Comment by tboerger** [comment]
Closed in favor of https://github.com/gogits/gogs/pull/2372

**Pull request closed without merging**
