### PR TITLE
Fr translation | Update

### PR DESCRIPTION
**Pull request by Darlelet**
minor changes to improve translations' understandability and quality

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

However please read: https://gogs.io/docs/features/i18n

**Comment by Darlelet** [comment]
My bad, didn't see this page :/
So I just need to review those changes using crowdin?

**Comment by Unknwon** [comment]
Exactly :D

**Comment by Darlelet** [comment]
I see, it works like Twitter translation center :)

**Comment by Unknwon** [comment]
Ha~ never used Twitter one, but this kind of system should be similar.

**Comment by Darlelet** [comment]
Indeed.
Done, everything is reviewed :)

**Comment by Unknwon** [comment]
Well done, thank you!

**Pull request closed without merging**
