### PR TITLE
fix lines highlighting at diff view

### PR DESCRIPTION
**Pull request by makhov**
Now it works:
init commit 5743f50e2c gogs go git service

### CODE REVIEW

**Comment by Unknwon** [comment]
Very awesome, thanks!

Is it highlighting multiple selected lines?

**Comment by makhov** [comment]
Yes, it is.

**Comment by Unknwon** [comment]
Merged, thanks again!

**Comment by Unknwon** [comment]
It seems broken normal code view selection...

**Comment by Unknwon** [comment]
Thanks your PR, and I've made some fixes(ugly but at least work right now) to `dev` branch and continue looking for your help!

The code you want to change is: https://github.com/gogits/gogs/blob/dev/public/ng/js/gogs.js#L206-L275

PS: Single line of highlighting in diff page is working, but now uses hashtag `#diff-{$i}L{$j}{$k}`.

Here is one issue we're facing:

I'm not really good at JS but I'm trying. We want to have multiple lines highlighting to be in the format of `#diff-{$i}L{$j1}{$k1}-L{$j2}{$k2}`, not sure if it's possible.

We can open a separate issue for this matter.

**Comment by makhov** [comment]
Ok, I'll try to fix multiple lines highlighting today.

**Pull request merged**
