### PR TITLE
Make Signup button display configurable - #884

### PR DESCRIPTION
**Pull request by nicolai86**
See #884 for the original request. I'd love some feedback for the tiny CR since it's my first.

### CODE REVIEW

**Comment by nicolai86** [comment]
I left out all the locales because I have to look them up yet. Will add those soon…

**Comment by nicolai86** [comment]
We now have the translations as well, except for lv and zh-HK

**Comment by Unknwon** [comment]
Thanks your PR!

But we don't do translation in here: see readme, except for English.

**Comment by nicolai86** [comment]
@Unknwon should I leave the new key for every language, or just revert the last commit except for the english translation?

**Comment by Unknwon** [comment]
Actually it doesn't mattar, non-English files will be eventually overwritten. 

Your PR looks good otherwise, will merge soon. :)

**Comment by nicolai86** [comment]
Cool. I'll leave the PR as is then :)

**Comment by Unknwon** [comment]
Merged, thanks again!

**Pull request merged**
