### PR TITLE
Lighter icon colors for repo files

### PR DESCRIPTION
**Pull request by silverwind**
Small visual change to file icon colors:

### Before
before

### After
after

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

Can you give a more complete screenshot of full page?

**Comment by silverwind** [comment]
Not much changed except the icon colors. The avatar rendering is a Firefox bug with the `screenshot` console commmand in case you're wondering :)

## before
before
## after
after

**Comment by Unknwon** [comment]
>... if it is not related to any particular issues, explain why we should not reject your pull request.

**Comment by silverwind** [comment]
I think you should accept it because I feel the current near-black icons feel a bit harsh to me, and because it's the same color scheme GitHub uses for repo icons.

**Comment by silverwind** [comment]
Screenshot from GitHub for comparision:



I could change the shade of blue if you like. Currently I'm using the same shade that is used for links.

**Comment by Unknwon** [comment]
OK, make sense.

**Pull request merged**
