### PR TITLE
Formatting and update copyrights

### PR DESCRIPTION
**Pull request by farazfazli**
Fix formatting using ```gofmt -s -w .``` and update copyright notices.

### CODE REVIEW

**Comment by bkcsoft** [comment]
You should probably read this ^.^ http://stackoverflow.com/a/2391555

**Comment by andreynering** [comment]
Maybe it should be `2014-2016`.

**Comment by farazfazli** [comment]
Yeah, I will change it to 2014-2016, that's better.

**Comment by bkcsoft** [comment]
has there been substantial change in all those files over 2015/16? otherwise you should just leave them at 2014. The year is kinda m00t for something that's tracked on github though :smile:

**Comment by farazfazli** [comment]
@Unknwon What are your thoughts?

**Comment by Unknwon** [comment]
Hi @farazfazli , thanks your PR!

But Gogs uses the "Go"'s way, which only states the start year of the file.

**Comment by Unknwon** [comment]
Close due to lack of feedback.

**Pull request closed without merging**
