### PR TITLE
Fixes #1071 - Web editor for repository files (Create new, edit, rename, delete)

### LINKED ISSUE #1071: Web editor for repository files
so that folks can easily make edits to files in a git repository from their browser without having to clone a whole repo

### PR DESCRIPTION
**Pull request by richmahn**
* NOTE: This also requires the PR #12 (https://github.com/gogits/git-module/pull/12) for git-module for handling branches
* NOTE: I renamed font-awesome, semantics and simplemde just so we don't need the version numbers in path to them (they have version in their headers) so that in the templates/base/head.tmpl we don't need to change it, as that causes problems with custom/templates/base/head.tmpl if it has been copied there. I left the version number in the jquery library though.

* Adds create new, edit, rename and delete feature for files
* Uses CodeMirror for editing files (if an MD file it uses the SimpleMDE editor)
* Moves workingPool out of the wiki.go file so it can be used for repos as well

Feel free to code review and give constructive criticism. My first addition with Go Lang. Thanks.

### CODE REVIEW

**Comment by bkcsoft** [comment]
Without checking the code, AWESOME!!! :smiley:

I would've prefered to remove SimpleMDE in favour of CodeMirror, since SMDE is a stripped down version of CD, which would lead to less cruft and remove possible collisions between the two, but that can be fixed later :smile:

**Comment by leitzler** [comment]
Nice!

With 166 files changed in one commit it's a bit hard to do any kind of code review.
I have no experience of codemirror, but do you really need all those files? If so, it would be a lot better to add them as a separate commit.

Also, there are a few files where every line has changed, are you using different end-of-line or something? Please fix those too so that diffs only show actual changes, and it will be a lot easier to do code review.

**Comment by megadr01d** [comment]
@bkcsoft Absolutely agree. CodeMirror takes care of Markdown files as well as any other format.

Besides, over the years, Markdown has gained a sort of special reputation that I do not get. It's still supposed to be a plain text formatting syntax, easy to write and understand and focused on keeping the hands on the keyboard, and yet we have transformed Markdown editors back into Rich Text editors, with all sorts of toolbars and buttons and preview panes, etc. It just lost its mojo.

**Comment by richmahn** [comment]
I see all the feedback on the SimpleMDE, yet I couldn't figure out how to then use CodeMirror to have the tool bar with buttons, unless there is an extension for that. Our content editors, who don't know code, need to have a WYSIWYG for editing manuals with this, the whole purpose we are using Gogs (we use GIthub for code). So any thoughts on how to better set up CodeMirror to have a MD toolbar?

**Comment by richmahn** [comment]
And should we really be changing the editor for the Wiki?

**Comment by richmahn** [comment]
166 changed files is because of how many files come with CodeMirror...a js file for each programming language/file type.

**Comment by binford2k** [comment]
@richmahn a PR like this would be easier to review if the commit vendoring the plugin was a single commit and your work was a separate commit.

**Comment by richmahn** [comment]
The request we had that editing files should be just like the Wiki...so in short, would this be possible with CodeMirror? I tried, and couldn't get the editor to look the same, so that is why if it is a .md file it uses SimpleMDE.

You can try what I have done on our testing site: http://test.door43.org:3000

**Comment by richmahn** [comment]
@binford2k Good point, but feel too late now, and of course I had to test my changes with CodeMirror before determining if it worked or not. But yes, could have backtracked and done things differently. Should I? I'm not that familiar with working on big projects (multiple people, code review, etc) with GitHub, so as I said, constructive criticism is welcome. Thanks!

**Comment by bkcsoft** [comment]
You can move the commited files (non-codemirror) to a new commits and
--force push to your branch :trollface:

**Comment by richmahn** [comment]
I'm guessing Travis-CI is failing because I also made changes to gogits/git-module and thus the gogs binary can't be compiled. What is the proper way to make a PR where it depends on a PR for another project?

**Comment by bkcsoft** [comment]
There's a bunch of configs for the wysiwyg-thingie.

And yes, mention the PR # in this PR :trollface:

**Comment by richmahn** [comment]
@bkcsoft I believe I did mention it...just Travis doesn't see it. :stuck_out_tongue: AI still needs much improvement in this world

I'll look into the configs.... I figured this would be a progressive code-review-fix cycle to get this working. Only have so much time, so didn't have much time to go into CodeMirror...I'm surprised I was able to get it to change the highlighting based on the filename (which can be changed when editing a file) as quickly as I did.

**Comment by richmahn** [comment]
@everyone 
So as I just said, this will probably be progressive, especially since this was the first time I ever coded such indepth for Gogs. 
Here are some issues I need your eyes on, and even help in fixing if you want to make a PR to my fork:

* Is every thing I did secure? i.e. Can only those who own the repo or have write access in an Org create, edit and delete the file?
* What

**Comment by richmahn** [comment]
@everyone 
So as I just said, this will probably be progressive, especially since this was the first time I ever coded such indepth for Gogs. 

Here are some issues I need your eyes on, and even help in fixing if you want to make a PR to my fork:

- [ ] Is every thing secure? i.e. Can only those who own the repo, or have write access in an Org, create, edit and delete the file?
- [ ] What about two people editing a file at the same time? Or deleting a file in one window and then commit it in another? (have yet to test these)
- [ ] Are branches handled properly at all times? (You can't create branches in Gogs, but can work with existing ones that you made locally and pushed)
- [ ] Anything else?

**Comment by andreynering** [comment]
@richmahn I didn't saw the code but gave a fast try. Very good job! It is working fine as is.

In the future, we may look to integrate it with the [editorconfig file](http://editorconfig.org/) as [GitHub does](https://github.com/RReverser/github-editorconfig#readme), to know what tab size use, and if tabs or spaces, etc. (But don't worry about this for now).

**Comment by bkcsoft** [comment]
Ooh, Travis can't pull in external PRs unfortunately.

**Comment by bkcsoft** [comment]
For editing at the same time, create a unique branch for each, merge on
Save. On merge-conflicts, inform and handle :)

**Comment by strk** [comment]
feature request for Gogs: accept external PRs :)   [ from any repo ]

**Comment by richmahn** [comment]
Ok, I have redone my whole commit and so now there are two commits in this PR, one for the CodeMirror plugin and the other is all the code I wrote for this.

**Comment by richmahn** [comment]
@andreynering Thanks for giving the code a fast try! If you check it out, I reworte history, so do a clean install from my develop branch. I cleaned up a lot of stuff as well.

yes, it allows changing the file name to a subdirectory, yet doesn't handle removing a directory (putting file in parent directory) like Github does. I could have just put the whole path in the field and not written anything before it except the repo name, but thought I would leave it like this and then work on another feature to use JavaScript to allow removing directories from the path.

We also need to be able to upload files, such as image and other binaries, like PDFs as it is now able to handle. Anyone interested in working on that feature (put the button next to the New File button by copying the form tag and placing it after)

Again, all is live at test.door43.org:3000 so if any of you want to create an account and play with it, feel free...post your findings/thoughts here.

**Comment by richmahn** [comment]
I see I need to make sure file names are valid. Will make a fix for it.

**Comment by richmahn** [comment]
I did some fixing of filenames. It appears that actually anything (except for / and a space on its own or at the beginning or end) can be used in a file name, it was just URL encoding that was messing things up. 

I still have yet to put in support to tell the user if they entered a name of a file that already exists if making a new file or renaming a file...not sure how to properly turn with an error other than a 500 or 404 error.

**Comment by Lafriks** [comment]
One thing I noticed that new file/edit/delete buttons are shown even when user has read only rights. In such case they sholdn't be visible

**Comment by richmahn** [comment]
@Lafriks Are you sure that's always the case? They're not grayed out with a hover message? Please give a page where they are not grayed out but should be for you.I did it exactly like Github did, explaining why they can't edit.  This is also so we can eventually have it so when they edit they can fork. Always refer to how Github does it.

**Comment by richmahn** [comment]
@everyone
The latest commit (which didn't get my user name but my Gogs account even though I am pretty sure I commited with my user name, odd) finally has better handling when you use file names for your new (or existing) file that already exists in the repo.

**Comment by richmahn** [comment]
@everyone
Still interested in anyone's feedback. I have now added a way to commit to a new branch when editing a file. (like at the bottom of a Github edit file form)

**Comment by joubertredrat** [comment]
hi guys,

this is results from my test
* Edit worked fine with js and php files
* tab go to front normally (tab), but don't go back (shift + tab), you need to use backspace or left arrow to return cursor.
* on edit php, js and css files here, highlight syntax is fine.
* Create new file worked fine here.

**Comment by orware** [comment]
Just tested on your door43 site.

This is probably just because of the early stage of things, but the new_file button seems awkwardly placed at the moment (on the main page for a repo...the placement on the subpages to the far right side look ok to me).

Functionality of adding the new file appeared to work ok, but the Preview pane is a bit off (it didn't seem to pick up a newline correctly as expected in my quick PHP test file).

For example, try this out on your test site and go to the Preview pane (the "echo" line shows up next to the starting PHP tags), compared to the GitHub Preview Pane:
```
<?php
echo "Hello World";

?>
```

The edit file option and create a new branch options both seemed to work just fine (though I'm not sure about the immediate redirect to create a pull request after editing one file...others may feel differently, it threw me off for a second and I just ended up cancelling out of that screen).

**Comment by jakimfett** [comment]
Is the text here going to be localized? I was a bit confused as to what it meant...assume it's "commit to master" and "commit to new branch"?
commit_branch_text

**Comment by richmahn** [comment]
Hmm, that text should be localized, but apparently when I last cleared my dev copy out and pulled from my fork it didn't build the bindata.go again.

**Comment by jakimfett** [comment]
How much info do you want on minor usability stuff? 
Eg, "after forking a repo, when you attempt to re-edit the original repo, it still takes you through the forking form". Mostly minor input stuff, dunno how focused you are on which aspects of the editing features.

**Comment by richmahn** [comment]
@orware Great response, thanks. A lot of what you wrote about being "odd" comes from Github, although the button to Create a new file is actually floating to the right. I tried to do that, as you will see it float to the right if there is no URL select box (home page of a repo)...it is actually floating right, even though it is in the middle. Not sure why the URL select box pads so much to the left.

When you edit a file on Github and make a branch, it tells you as my text does too (oh, right, we estableshed that the locale text isn't compiled, try again soon after i write this) that it is to make a branch and then do a pull request. Let me know if you experience this behavior on Github too or if I got it wrong.

The "Preview" pane is simply a rendering of Markdown, and of course will show HTML tags, but leaves <? > tags to display. Until we get some better rendering modules in the api/v1 directory, markdown is all we got.

I actually want to make a Diff pane (which is the "Preview Changes" on Github) to show diff, but don't have time for that right now.

**Comment by richmahn** [comment]
@jakimfett Yeah, I noticed those kind of things too...it was just a quick fix to make a link to the fork creation page. Would have to do some logic to know if they have a fork or not. Ideal is to get it to behave like Github does.

**Comment by richmahn** [comment]
@jakimfett @orware Try again, the branch selection on the edit page should have the proper text now.

**Comment by jakimfett** [comment]
@richmahn Looks good as of a minute or two ago. Thanks!

Makes sense on the forking bit, and it's relatively minor because clicking through just takes you to the existing fork.

**Comment by jakimfett** [comment]
@richmahn - I was looking back at your list of stuff you specifically want people to check for:
* Security, from a "can I click around and do stuff I shouldn't be able to" perspective seems good, I haven't tried editing POST values or hitting URLs manually, but I think that's beyond the scope of what you were asking.
* Two or more people editing a file at the same time results in the last person to save being the authoritative copy...nothing gets merged. Editing a file that got deleted results in "The file you are editing no longer exists in the repository" on save.
* "are branches handled properly" not entirely certain what you're looking for here, but creating a new branch seems to be possible via the UI, at least by putting a name in the "search for branches" and clicking "create from master"
branch_test

* So far, nothing else is needed...just having plain editing is fantastic, and the added bonus of markdown rendering is a big plus. I'm really looking forward to this improvement.

**Comment by richmahn** [comment]
@jakimfett regarding it always going to the forking form when you try to edit a file you can't edit (someone else's repo), you do know you can fork it not only to your own account but a organization, right? How would I know if they don't want to make a second fork?

**Comment by lavvy** [comment]
Hey @richmahn have you tried to investigate why the travis build is failing

**Comment by richmahn** [comment]
@lavvy Already talked about here...doesn't have the classes needed in git-module because that needs to be pulled from my fork as well

**Comment by richmahn** [comment]
@lavvy @everyone - Latest commit adds ability to upload files to your repo. Please test! http://test.door43.org:3000

**Comment by andreynering** [comment]
@richmahn Again, great work. The file upload seems to be working very well.

I just got a template error while seeing commits:

http://test.door43.org:3000/andreynering/test/commits/master

```
template: repo/branch_dropdown:34:169: executing "repo/branch_dropdown" at <$.TreeName>: invalid value; expected string
```

**Comment by richmahn** [comment]
@andreynering I found that bug too when doing my tests. Fixed now. Thanks for checking!

**Comment by joubertredrat** [comment]
@richmahn very nice feature for upload files, on my tests here, worked fine, I will continue to test.

**Comment by atomi** [comment]
If I merge this PR into develop and try to build the docker container it fails
```
github.com/gogits/gogs/models
# github.com/gogits/gogs/models
models/repo.go:416: unknown git.CloneRepoOptions field 'Branch' in struct literal
models/repo.go:421: undefined: git.Checkout
models/repo.go:421: undefined: git.CheckoutOptions
models/repo.go:429: unknown git.PullRemoteOptions field 'Remote' in struct literal
models/repo.go:430: unknown git.PullRemoteOptions field 'Branch' in struct literal
models/repo.go:445: undefined: git.Checkout
models/repo.go:445: undefined: git.CheckoutOptions
models/repo.go:2200: undefined: git.MoveFile
make: *** [build] Error 2
Makefile:20: recipe for target 'build' failed
The command '/bin/sh -c ./docker/build.sh' returned a non-zero code: 2
```

**Comment by atomi** [comment]
@richmahn I've been testing your recent commits and I have to say I prefer the editor to expand to size the browser the way CodeMirror does. It would also be nice to be able to ctrl+enter to save. But that should be delegated to the editor you finally decide on. Great work so far though. Thanks.

**Comment by richmahn** [comment]
Thanks fore everyone's feedback. As this has gotten kind of messy with it having multiple commits to fix bugs and adds additions to this feature, and as it was on my develop branch, I have changed the branch I'm working on this from and squashed/rebased back to just two commits. See Pull Request #3151 to continue testing and discussion.

If you are testing this on your server, please check out my fix-101-web-editor-for-repository-files branch. Can continue to see this and other features I'm working on at http://test.door43.org:3000

**Pull request closed without merging**
