### PR TITLE
Repositories panel in personal settings

### PR DESCRIPTION
**Pull request by master-d**
This is my first attempt at adding a personal repositories panel under "User Settings" (Issue #4277).  
One of the things that needs to be reviewed is my use of the ```[admin]``` localization variables since these do not exist under ```[settings]``` yet.  I'm not sure what the process is for adding to the localization files or if you even want to bother with that for this PR or not.  

Currently, it will only display repositories that the logged in user owns and will only allow the logged in user to delete his own repositories.

### CODE REVIEW

**Comment by Unknwon** [comment]
Hi, can you do rebase instead of merge?

**Comment by Unknwon** [comment]
Can you attach a screenshot?

**Comment by master-d** [comment]
repositories-gogs

**Comment by Unknwon** [comment]
Thanks for the screenshot!

1. Do not 
1. Delete should not allowed.
2. Not checked code but all accessible repos should be listed.
3. Panel heading should be same as navbar, in English it's **Repositories**, make sure use the same i18n locale string.
4. Navbar should be highlighted.
5. I more prefer the way GitHub does:

image

**Comment by master-d** [comment]
Gotcha.  I can make these adjustments. I'm assuming you don't want the delete button available even for user owned repositories?  And you only want this formatting for the User Settings repositories page right and not the admin page?

**Comment by Unknwon** [comment]
>I'm assuming you don't want the delete button available even for user owned repositories?

Correct.

>And you only want this formatting for the User Settings repositories page right and not the admin page?

This page is no relation to admin page.

**Comment by master-d** [comment]
I updated some the html format to match the github template a little better, but haven't hooked up the "leave" button yet and had a few questions about this button:

1. Should the "leave" button appear for shared team repos as well as collaborative repos or only for collaborative repos?
2. What action should be performed when the user clicks "leave" and clicks "yes" to confirmation popup? (this kinda depends on the answer to 1)
3. Should I display the "forked from" information shown in your github example if the repository has been forked?

repositories-gogs

**Comment by Unknwon** [comment]
Thank you!

**Comment by master-d** [comment]
@Unknwon I wasn't done with this PR yet because the leave button isn't wired up.  We're you gonna do this yourself?  I don't mind doing it, but was hoping you could answer the questions I made above.

**Comment by Unknwon** [comment]
Ah... that's what I thought, I'm working on it currently.

**Comment by master-d** [comment]
Ok, also check the condition that determines whether the leave button is displayed or not.  I think it is currently displaying on all non-public repositories that you don't own and that may be incorrect.

**Comment by Unknwon** [comment]
Thanks, I've noticed, almost done.

**Pull request merged**
