### PR TITLE
Added supported of 'AUTH LOGIN'

### PR DESCRIPTION
**Pull request by haoyixin**
i've been missing a 'r' in previous, lol~

### CODE REVIEW

**Comment by haoyixin** [comment]
this is for https://github.com/gogits/gogs/issues/1514

**Comment by Unknwon** [comment]
Oops, forgot to mention that would you mind to re-PR to `develop` branch?

**Comment by haoyixin** [comment]
never mind, it's up to you :-)

**Comment by Unknwon** [comment]
Cool! So can you close this and start a new to `develop`?

**Pull request closed without merging**
