### PR TITLE
Only show activities and repositories on the dashboard, that the user has access to

### PR DESCRIPTION
**Pull request by fnkr**

### CODE REVIEW

**Comment by Eriner** [comment]
:+1: for fixing this issue. Thanks!

**Comment by Unknwon** [comment]
Thanks for the PR!

But I think the core problem is why a user would receive feeds from a repository that s/he does not have access to?

**Comment by fnkr** [comment]
What do you mean?

Old behaviour: show repo/activity, if the user has joined the org.
New behaviour: show repo/activity, if the user has access to it (= is in a team together with the repo).

It's exactly the same thing as in #2527 and #2530.

**Comment by Unknwon** [comment]
No, it is not the same thing.

If you don't have access to a repo, how can you receive feeds from that?

**Comment by fnkr** [comment]
In order to access a private organization repository, you need to be in a team that has (at least) read access to that repository. The problem: right now, this doesn't apply to feeds. You get feeds for all repositories in your orgs. It doesn't matter if you have access to that repo or not (read: if you are in a team that has access to that repo or not).

**Comment by Unknwon** [comment]
> You get feeds for all repositories in your orgs.

No, only ones you watched I think.

**Comment by fnkr** [comment]
That's not true. Example: _user2 is **only** in _team1. _team1 has **only** access to _repo1. BUT: right now, _user2 can view activities from _repo2 on the org dashboard. _user2 can't view _repo2. But he can see it's activities.

before

**Comment by Unknwon** [comment]
That's why I said:

> But I think the core problem is why a user would receive feeds from a repository that s/he does not have access to?

**Comment by fnkr** [comment]
What do you mean? The user get's all feeds that match the query?

**Comment by Unknwon** [comment]
We need to stop user receiving feeds from repos that they do not have access to.

**Comment by fnkr** [comment]
Yeah, this is that this PR does, isn't it?

**Comment by Unknwon** [comment]
Sorry, I really mean `receive` when I say `get`.

Why should feeds for these users be ever generated if they don't have access?

**Comment by fnkr** [comment]
The feeds you see when viewing an organization dashboard are stored under the user id of the organization, not your own user id.

**Comment by Unknwon** [comment]
Ah, I see the problem now... Thank you! My bad.

**Pull request merged**
