### PR TITLE
Do not change page on logout

### PR DESCRIPTION
**Pull request by strk**
Complements the fix to #3089 (for the logout action)

### CODE REVIEW

**Comment by Unknwon** [comment]
It is not guaranteed you still have access to same page after logout.

**Comment by strk** [comment]
On August 12, 2016 6:48:27 PM CEST, "无闻" <notifications@github.com> wrote:
>It is not guaranteed you still have access to same page after logout.

Yes, and it may be confusing. But so it is when the url to an unaccessible repo is given. I think the confusion should be reduced enhancing the response page, as it currently is a 404 not found wheread it should be so mm ething like "forbidden" instead. It is good to stay on the same psge because then a further login would make such page accessible again
--strk;

Sent from device with lame keyboard. Please excuse my brevity.

**Comment by Unknwon** [comment]
It is designed to show 404.

**Comment by strk** [comment]
For the record, it looks like GitHub behaves exactly as Gogs on signout, that is, it always redirects to the homepage. If Gogs wants to behave exactly the same, this PR can be closed (I don't have a major problem with that)

**Comment by bkcsoft** [comment]
For the record, so does GitLab and BitBucket as well :)

**Pull request closed without merging**
