### PR TITLE
Added LDAP simple auth. support

### PR DESCRIPTION
**Pull request by SergioBenitez**
As discussed in #1524, this pull request adds a simple authentication LDAP auth method to Gogs. 
This pull request also refactors the main login function in `models/login.go` and the auth form javascript code in `public/ng/js/gogs.js`.

From the README:
> LDAP simple authentication does not utilize a Bind DN. Instead, it binds directly with the LDAP server using the user's supplied credentials. If the bind succeeds and no filter rules out the user, the user is authenticated.

The simple auth LDAP form looks as follows:
screen shot 2015-09-04 at 9 20 59 pm

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks!

**Comment by SergioBenitez** [comment]
Checking in on this. Let me know if you need any input @Unknwon.

**Comment by Unknwon** [comment]
Oops, didn't notice this has conflicts :mask:

Some other things are needed to be done before this, sorry about waiting!

And if you don't mind, would you like to update this PR and resolve conflict?

**Comment by SergioBenitez** [comment]
Done.

**Comment by Unknwon** [comment]
@SergioBenitez thank you, appreciate!

**Comment by Unknwon** [comment]
Merged! Thanks again!

**Pull request merged**
