### PR TITLE
Add AddCollaborator API Endpoint

### PR DESCRIPTION
**Pull request by roblabla**
Adds the `PUT /repos/:username/:reponame/collaborators/:collaborator` endpoint, based on https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator, allowing the API to add collaborators to a repository.

I messed up #2775 (it was opened on the wrong branch).

**EDIT**: now implements `permission` like github's api, taking one of three arguments, "pull", "push" or "admin".
I can squash into one commit if that is prefered.

### CODE REVIEW

**Comment by Unknwon** [comment]
Please sign the CLA.

**Comment by roblabla** [comment]
Done

**Comment by Unknwon** [comment]
Somehow has conflict...

**Comment by roblabla** [comment]
Fixed :)

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
