### PR TITLE
Additional API support for milestones

### PR DESCRIPTION
**Pull request by lstahlman**
Implements the ability to manage repository milestones and issue milestones via the API.

This PR depends on gogits/go-gogs-client#39

### CODE REVIEW

**Comment by lstahlman** [comment]
# Milestones

## List milestones for a repository

```
GET /repos/:owner/:repo/milestones
```

##### Response

```
Status: 200 OK
Content-Type: application/json
```

```json
[
  {
    "id":2,
    "state":"closed",
    "title":"1.0",
    "description":"Initial release",
    "open_issues":0,
    "closed_issues":12,
    "closed_at":"2016-07-04T14:37:05-07:00",
    "due_on":"2016-07-04T00:00:00-07:00"
  },
  {
    "id":4,
    "state":"open",
    "title":"1.0",
    "description":"Fix pack 1",
    "open_issues":5,
    "closed_issues":3,
    "closed_at":null,
    "due_on":"2016-09-06T00:00:00-07:00"
  }
]
```

## Get a single milestone

```
GET /repos/:owner/:repo/milestones/:id
```

##### Response

```
Status: 200 OK
Content-Type: application/json
```

```json
{
  "id":4,
  "state":"open",
  "title":"1.0",
  "description":"Fix pack 1",
  "open_issues":5,
  "closed_issues":3,
  "closed_at":null,
  "due_on":"2016-09-06T00:00:00-07:00"
}
```

## Create a milestone

Only users with write access to a repository can perform this action.

```
POST /repos/:owner/:repo/milestones
```

##### Parameters

|Name|Type|Description|
|----|----|-----------|
|title|string|The name of the milestone|
|description|string|Description of the milestone |
|due_on|time|The due date e.g., "2016-09-06T00:00:00-07:00" |

##### Example

```json
{
  "title":"1.0.1",
  "description":"Fix pack 1",
  "due_on":"2016-09-06T00:00:00-07:00"
}
```

##### Response

```
Status: 201 Created
Content-Type: application/json
```

```json
{
  "id":4,
  "state":"open",
  "title":"1.0.1",
  "description":"Fix pack 1",
  "open_issues":0,
  "closed_issues":0,
  "closed_at":null,
  "due_on":"2016-09-06T00:00:00-07:00"
}
```

## Edit a milestone

Repository owners and users with write access can perform this action.

```
PATCH /repos/:owner/:repo/milestones/:index
```

##### Parameters

|Name|Type|Description|
|----|----|-----------|
|title|string|The name of the milestone|
|description|string|Description of the milestone |
|due_on|time|The due date e.g., "2016-09-06T00:00:00-07:00" |

If a parameter is empty, that part of the label will remain unchanged

##### Example

```json
{
  "due_on":"2016-09-15T00:00:00-07:00"
}
```

##### Response

```
Status: 200 OK
Content-Type: application/json
```

```json
{
  "id":4,
  "state":"open",
  "title":"1.0.1",
  "description":"Fix pack 1",
  "open_issues":0,
  "closed_issues":0,
  "closed_at":null,
  "due_on":"2016-09-15T00:00:00-07:00"
}
```

## Delete a milestone

Only users with write access to a repository can perform this action.

```
DELETE /repos/:owner/:repo/milestones/:id
```

##### Response

```
Status: 204 No Content
```

**Comment by lstahlman** [comment]
# Issue Milestones

## Get the milestone for an issue

```
GET /repos/:owner/:repo/issues/:index/milestone
```

##### Response

```
Status: 200 OK
Content-Type: application/json
```

```json
{
  "id":2,
  "state":"closed",
  "title":"1.0",
  "description":"Initial release",
  "open_issues":0,
  "closed_issues":12,
  "closed_at":"2016-07-04T14:37:05-07:00",
  "due_on":"2016-07-04T00:00:00-07:00"
}
```

## Set an issue's milestone

Only users with write access to a repository can perform this action.

```
POST /repos/:owner/:repo/issues/:index/milestone
```

##### Parameters

|Name|Type|Description|
|----|----|-----------|
|id|int|ID of the milestone|

##### Example

```json
{
  "id": 4
}
```

##### Response

```
Status: 200 OK
Content-Type: application/json
```

```json
{
  "id":4,
  "state":"open",
  "title":"1.0",
  "description":"Fix pack 1",
  "open_issues":5,
  "closed_issues":3,
  "closed_at":null,
  "due_on":"2016-09-06T00:00:00-07:00"
}
```

## Remove an issue's milestone

Only users with write access to a repository can perform this action.

```
DELETE /repos/:owner/:repo/issues/:index/milestone
```

##### Response

```
Status: 204 No Content
```

**Comment by Unknwon** [comment]
Please sign the CLA.

**Comment by Unknwon** [comment]
Thanks!

**Comment by Unknwon** [comment]
Just a note, issue-milestone endpoints will be removed because you can get these info with issue APIs.

**Pull request merged**
