### PR TITLE
Add a default repository permission to orgs

### PR DESCRIPTION
**Pull request by roblabla**
This patch allows the org admin to set the default access mode of the Org's member to all of the org's Repositories.

### CODE REVIEW

**Comment by roblabla** [comment]
hmm. I think a better way to do this might be to leverage the existing "team" infrastructure. Having an invisible "default" team with all users/repos that the toggle would act on. What I currently have breaks the "Collaborative Repositories" section, and probably a few other things.

I'll try to implement this.

**Comment by Unknwon** [comment]
Thanks your PR but does not seem a good idea...

**Comment by roblabla** [comment]
Erm, yeah ? That's exactly the use-case for it. It allows an org to give permissions on all of its repositories (including private) to all its members. Github has a similar feature : https://github.com/organizations/gogits/settings/member_privileges . The default, obviously, is to give no permission at all.

The use-case is, in my company, every employee is allowed to access all repositories. Before this PR, I had a "members" team that contained all repositories and all members. However, it meant that I had to handle that manually, and it was a hassle. Now, I just allow every member of the org to have "read" permission, and that's it.

**Comment by Unknwon** [comment]
OK, will take a deep look.

**Comment by Unknwon** [comment]
Since now we're able add organization member as repository collaborator, I'm closing this.

**Pull request closed without merging**
