### PR TITLE
push + pull now works with reverse proxy + basic auth on apache 2.4

### PR DESCRIPTION
**Pull request by dl5rcw**
related to #2891 
I posted a gist before and now created this pull request as this could be more convenient to you.

I use gogs with reverse proxy and basic auth. Users are auto created. 
http pull and push did not work, so I started to look in the code.

### CODE REVIEW

**Comment by LefsFlarey** [comment]
I don't get it?

I also frequently use my Gogs instance, on a docker, behind a Apache webserver that forwards the requests and I've never encountered a problem with git push/pull.

**Comment by dl5rcw** [comment]
@LefsFlarey
Do you use reverse proxy including authentification?
1.)	configured the reverse proxy. 
2.)	Apache also handles user auth. The user passed successfully to gogs, auto-create was okay, too. 
3.)	But doing a git push/pull on the http url failed due to authentication – as described in #2891.
Reading #2891, I felt not alone with that. I grabbed the idea posted there and tweaked/updated the differences to match the current gogs code. It then worked splendid. Apache 2.4 is reverse proxy and checks the authentication. The user is then passed to gogs. The code I modified compiles with the latest gogs branch and it now works.

**Comment by LefsFlarey** [comment]
Sorry, I do not really understand what this pull request is about, so I'll leave it to the more experienced people like @Unknwon and @bkcsoft to figure it out :)

**Comment by dl5rcw** [comment]
Referencing the other thread, I thought this issue is known.
We use SSO (AuthBasicProvider dbd, Apache 2.4, Location /gogs AuthType Basic)
Reverse Proxy is pointing to /gogs.
[security]
REVERSE_PROXY_AUTHENTICATION_USER = X-WEBAUTH-USER
[service]
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true

Everything besides git pull/push via http link failed. I did not check a private repo and clone. 
With the code posted by @joe-french - which needed modification and tweaks to compile with the latest repo version - everything worked. Please read his ticket, too.

**Comment by strk** [comment]
@dl5rcw would you consider moving this to http://github.com/go-gitea/gitea ?

**Comment by dl5rcw** [comment]
it is merged into https://github.com/go-gitea/gitea. I will close this one as nothing happened.

**Pull request closed without merging**
