### PR TITLE
French Grammar fix in pulls.merged_title_desc

### PR DESCRIPTION
**Pull request by lpotherat**
Fixed grammar in pulls.merged_title_desc à => a

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks for the PR, but according to policy, I have to close this.

Quick ref: https://github.com/gogits/gogs/wiki/Contributing-Code

**Comment by lpotherat** [comment]
My bad, thanks for quick ref.
Fix is requested in Crowdin.
Keep Gogs great !

**Comment by Unknwon** [comment]
Approved, thanks!

**Comment by lpotherat** [comment]
I can wait ;).
I've added some other fixes on the fly in Crowdin.

Closed !

**Pull request closed without merging**
