### PR TITLE
Add support for .diff and .patch

### PR DESCRIPTION
**Pull request by odinuge**
Add the ability to get text-diff and format-patch by adding .diff or
.patch in the end of a commit url. Issue #2641

With the current behavior with the wildcard in the route, this is the only solution i see. There are probably more elegant ways to solve the problem, but that will require some rethinking. What is your opinion @Unknwon?

And "maxlines", that should not have any impact on this..?

### CODE REVIEW

**Comment by Unknwon** [comment]
@odinuge 

I've added a route for you: https://github.com/gogits/gogs/commit/60ae8ac3d2995d46156ead8ad93004801daad4ce#diff-da541ef36e39344f2e12bddd91d363e2R526

**Comment by odinuge** [comment]
Hi!

I did think about that, but that breaks the ability to use refs instead of sha1sum. [Here](https://try.gogs.io/odinuge/issue-2545-test/commit/master) is an example. Using regex instead of the wildcard is a good idea! I'll keep working on it, but I don't have more time today or tomorrow.

**Comment by Unknwon** [comment]
That use case was never part of the design.. maybe somehow supported, but not intended to.

**Comment by barracks510** [comment]
I've tested this after rebasing it to the latest develop branch and it works very nicely. Thanks!

**Comment by Unknwon** [comment]
PR has conflict...

**Comment by barracks510** [comment]
I've rebased the patch to the latest develop tree. You should be able to merge the PR without conflict.

**Comment by odinuge** [comment]
If you think it is ready, i can rebase it to the latest develop.

**Comment by Unknwon** [comment]
There are some changes on https://github.com/gogits/gogs/pull/3300 as well, you would have to update those at the same time.

**Comment by odinuge** [comment]
Rebased the PR.
New PR, see #3300..

**Pull request closed without merging**
