### PR TITLE
Display author's name on explore page

### PR DESCRIPTION
**Pull request by dhuan**
This simply changes the way the Explore page is displayed, allowing the viewer to see the author's name next to repository name.

### CODE REVIEW

**Comment by 5paceManSpiff** [comment]
:+1:

**Comment by 5paceManSpiff** [comment]
I'm thinking of running your fork of gogs until this is pulled in to upstream.  Would you be able to post a screenshot of the modified explore page? <3 thanks!

**Comment by dhuan** [comment]
@5paceManSpiff, this is what the explore page looks like when applying this change:
gogs

**Comment by sh4nks** [comment]
I think that it would look better if you add spaces around "/".

like:
```{{.Owner.Name}} / {{.Name}}```

**Comment by dhuan** [comment]
@sh4nks indeed it looks better if it's surrounded by spaces, I just updated so it looks that way.

**Comment by lunny** [comment]
Good job!

**Pull request merged**
