### PR TITLE
Fixes broken UI under supported resolution (1024x768) #5179

### PR DESCRIPTION
**Pull request by rokuu**
Fixes https://github.com/gogits/gogs/issues/5179

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks, will do a local checkout and test ASAP.

**Comment by rokuu** [comment]
I think I fixed all the tables that needed fixing  

[Files with Tables](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/gogits/gogs%24+%3Ctable+file:%5C.tmpl%24+)

**Comment by qwentytee** [comment]
@Unknwon @rokuu has this been reviewed yet?

**Comment by Unknwon** [comment]
@qwentytee not yet, you can checkout PR locally to try

**Comment by qwentytee** [comment]
@Unknwon LGTM, but needs testing on a production server populated with data like try.gogs.io

**Comment by Unknwon** [comment]
Thank you!

**Pull request merged**
