### PR TITLE
Fix negative issue count set by Check Repository Statistics

### PR DESCRIPTION
**Pull request by roblabla**
Please, make sure you are targeting the `develop` branch!

More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

num_issues and num_closed_issues don't contain the PR-issues.

### CODE REVIEW

**Comment by BurakDev** [comment]
Nice catch @roblabla

**Comment by tkausl** [comment]
The whole checking if it has to be updated and then updating it one by one is unnecessary. We could replace the whole block with just one execution of
```
UPDATE `repository` SET num_closed_issues = (SELECT COUNT(*) FROM `issue` WHERE repo_id = `repository`.`id` AND is_closed = 1 AND is_pull = 0)
```

**Comment by BurakDev** [comment]
@tkausl Is your query compatible with all database backend ? Don't forget that

**Comment by andreynering** [comment]
What do you guys think of not actually using this column, but count for the open issues when needed? So, no need to update it manually.

**Comment by tkausl** [comment]
@andreynering I already thought about that. Not sure why it was implemented like this, probably performance reasons.

**Comment by andreynering** [comment]
@tkausl Count queries are fast with proper index, I think performance wouldn't be a problem.

**Comment by Unknwon** [comment]
Thanks!

**Comment by Unknwon** [comment]
@andreynering It would be ideal, but since we can now keep this column value correct, I think it would be not be necessary.

**Comment by Unknwon** [comment]
@tkausl: @BurakDev pointed out one part of the reasons, another reason it would be nice to show which repository is been updated for debugging purpose. And since we only do this on start time and the loop is usually small (most of time 0), it would not hurt performance at all in my opinion.

**Comment by FGM** [comment]
Any suggestion about the best way to fix it once the database contains the incorrect values ? I currently have "Issues: -3" on Gogs 0.9.28.0527. Or will it automagically be fixed when the update is applied from the debian package ?

**Comment by Unknwon** [comment]
@FGM 

`the debian package ?` is out of our hands and have been failed to build latest Gogs for quite a while, but once you use latest Gogs connect to your existing database, it fixes automatically.

**Comment by FGM** [comment]
@Unknwon thank for the confirmation.

**Pull request merged**
