### PR TITLE
Dockerfile is added for RaspberryPi which is based on sander85/rpi-alpine image

### PR DESCRIPTION
**Pull request by raxetul**

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks, but can you re-PR to `develop` branch?

**Comment by tboerger** [comment]
I think suffixes separated with a dot are more conventional.

**Comment by Unknwon** [comment]
Yes, maybe change to file name `Dockerfile.rpi`?

**Comment by tboerger** [comment]
Like Dockerfile.armhf

**Comment by Unknwon** [comment]
What does `armhf` mean...?

**Comment by tboerger** [comment]
armhf is the architecture, in fact it's not limited to raspberry.

**Comment by Unknwon** [comment]
But the line 

`FROM rpi-alpine`

I suppose this only works for raspberry? Or maybe all `armhf` could work?

**Comment by raxetul** [comment]
ARM HF, ARM with hardware floating point supported linux kernel. I will
take care your purposes.

**Comment by Unknwon** [comment]
Any updates?

**Comment by raxetul** [comment]
I'm sorry that was busy, I will update this night(GMT+2).
22 Kas 2015 10:50 tarihinde "无闻" <notifications@github.com> yazdı:

**Pull request closed without merging**
