### PR TITLE
adding extra check on logpath

### PR DESCRIPTION
**Pull request by tjyang**
Extra checking on path of log file.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks, but can you re-PR to `develop` branch?

**Comment by tjyang** [comment]
sure, once I figured out how to pull against dev branch. git newbie here ;)

**Comment by Unknwon** [comment]
You can select branches while creating the PR :D

**Comment by tjyang** [comment]
Thanks, I submitted my PR against develop branch now.

On Sat, Oct 31, 2015 at 12:04 PM, 无闻 <notifications@github.com> wrote:

> You can select branches while creating the PR :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gogits/gogs/pull/1868#issuecomment-152750727>.
>



-- 
T.J. Yang

**Pull request closed without merging**
