### PR TITLE
Ipython notebook support

### PR DESCRIPTION
**Pull request by prinsherbert**
I'm sorry for making a mess of the conversation (this being the 3rd PR for the same feature)

I was more careful merging with newer stuff in the develop branch, I think I have done it right this time. Please let me know if anything is still off.

- https://github.com/gogits/gogs/pull/4068
- https://github.com/gogits/gogs/pull/4067

### CODE REVIEW

**Comment by Unknwon** [comment]
The `.less` looks good now!

**Comment by prinsherbert** [comment]
Good, that leaves a go file and two templates :)

**Comment by Unknwon** [comment]
Just noticed the PR include everything of **marked**, shouldn't we only need JS, CSS and some images? Tests, for example, are useless as dependency here.

**Comment by prinsherbert** [comment]
I simply added the whole 'release' of marked as provided on github, I would not know whether it's a good idea to delete parts.

**Comment by Unknwon** [comment]
You only need to as result of `build` or `dist`, like the [this](https://github.com/gogits/gogs/tree/master/public/plugins/dropzone-4.2.0). Not everything.

**Comment by Unknwon** [comment]
Ping?

**Comment by prinsherbert** [comment]
@Unknwon I admire your commitment to this PR-request, but please don't talk to me like I'm a networking interface.

Anyhow, I removed a significant amount of (superfluous) javascript and repulled the develop branch.

**Comment by Unknwon** [comment]
>but please don't talk to me like I'm a networking interface.

Sorry for any uncomfortable, it's a quick and common way on GitHub to verify if a thread still active.

New changes look good, merging. Thanks again!

**Comment by Unknwon** [comment]
OK, finally on demo! https://try.gogs.io/unknwon/ipython-notebooks

The only small problem is this file: https://try.gogs.io/unknwon/ipython-notebooks/src/master/nmf_topics.ipynb

The JS error seems **notebook.js** couldn't render it.

**Comment by prinsherbert** [comment]
@Unknwon No worries, I assumed no bad intend.

I think the `nmf_topics`-bug might be a notebook.min.js. A solution from our side might be to have graceful-degradation to the plain json-file if the notebook does not render. (Although I would guess nobody is really interested in the JSON in practice).

**Comment by Unknwon** [comment]
@prinsherbert roughly next Tuesday (2/14/2017).

**Comment by prinsherbert** [comment]
Cool, thanks!

**Pull request merged**
