### PR TITLE
add protected branch

### LINKED ISSUE #776: Protected branch
Reference https://about.gitlab.com/2014/09/29/gitlab-flow/
Reference https://code.google.com/p/gerrit/

Gogs should have a feature of protected branch. Let say `master` is a protected branch, then:
- Nobody can push directly to `master`
- Everybody\* can checkout/fork from `master`
- Everybody\* submit a merge request / code review request for his/her new branch (features/fixes)
- Everybody\* can comment/discuss the diff, preferable line-by-line
- Only those with "Reviewer" or "Supervisor" or "Senior" privilege can vote up/down on a merge request / code review
- A merge request can only be eligible to be merged to master when having at least [a number] 2 of up votes. This parameter should be defined in a config file, environment variable, or runtime argument, so that nobody, even master or supreme admin can bypass code review process by setting it to 1 and self-review their code.

*Everybody is any user with sufficient authorization to read a project `master` and write to their own name space.

### PR DESCRIPTION
**Pull request by ningdb**
Refer to gitlab to develop this functionality
Admin does not restrict
Owner is not restrict
write permission restrictions
fix #776

### CODE REVIEW

**Comment by strk** [comment]
@ningdb would you consider sending a version of this PR rebased to gitea/master ?
See https://github.com/go-gitea/gitea

**Comment by Unknwon** [comment]
Hi @ningdb , thanks for the PR! But I do really want to consider @strk 's idea because this PR is most likely not going to be merged as https://github.com/gogits/gogs/issues/776 assigned to myself to prevent any community contribution before I implemented the initial version.

**Comment by joelhy** [comment]
@Unknwon 
When will you implement the initial version?
#776 has been wanted since Dec 23, 2014. And lots of people are requesting for it.

**Comment by Unknwon** [comment]
Closed by https://github.com/gogits/gogs/commit/7e09d210ba421a1baf03ef7ba8770bebe8d28b72.

**Pull request closed without merging**
