### PR TITLE
Hide avatar tooltips unless you're looking at your own profile

### PR DESCRIPTION
**Pull request by jamesa**
This hides the tooltips and links to configure your profile picture, unless it's your profile. This also links directly to the profile image, similar to how GitHub does, if you're looking at another user's profile.

Also included a commit to change the size of the resized uploaded avatars, from 200px to 234px, like was talked about in issue #1107. But not sure if this is how you wanted this fixed!

### CODE REVIEW

**Comment by Unknwon** [comment]
Looks good, thanks!

**Comment by Unknwon** [comment]
https://try.gogs.io/unknwon is updated as well. :grinning:

**Comment by jamesa** [comment]
@Unknwon not sure why I get an error on that new statement on that link. Obligatory "works on my PC." :P

**Comment by Unknwon** [comment]
There is a template error, has pushed fix

**Comment by jamesa** [comment]
Thanks, I thought I had to compare IDs not names.

**Comment by Unknwon** [comment]
Normally, yes, compare ID.

But when there is no logged in user, `.SignedUser` is `nil` and Go template cannot compare with it. So it panics

**Pull request merged**
