### PR TITLE
Implement branch deletion on PR merge (as an option). Closes #3201.

### LINKED ISSUE #3201: Add option to delete source branch after merge
It would be nice if the source branch could get deleted when a pull request is approved (as an option). Bitbucket & gitlab both offer this feature.

### PR DESCRIPTION
**Pull request by tomsid**
- adds a checkbox for branch deletion near "merge" button
selection_007

- the checkbox will be disabled if the head branch is the default branch of the repository.

### CODE REVIEW

**Comment by Unknwon** [comment]
Somewhat duplicated to https://github.com/gogits/gogs/pull/3225?

**Comment by kmadel** [comment]
I prefer the UX of #3225 - the checkbox is not very intuitive.

**Comment by tomsid** [comment]
Indeed, didn't notice that PR.

In my opinion the ability to delete source branch should be given only at merging.

Lets consider an example:
1. User creates a branch, make changes and creates a PR.
2. PR merged without branch deletion
3. Later, the branch has been deleted manually.
4. Someone creates a branch with the same name (e.g. fix_issue) and make changes there.
5. An another contributor looks at merged PRs and see that the branch is still there. He thinks that the branch is stale and push's the button in order to delete this branch.
6. The branch with valuable changes is deleted.

So there is a possibility to delete a branch with new commits.

**Comment by Unknwon** [comment]
@tomsid good point!

Gogs stores the commitID that is being merged: https://github.com/gogits/gogs/blob/master/models/pull.go#L60

So we can check before deletion, and returns error if new commits have pushed.

**Comment by tomsid** [comment]
@Unknwon In that case the button is a good solution too.
So what solution do you prefer?

**Comment by Unknwon** [comment]
I prefer the button solution which delete branch after merged.

**Comment by tomsid** [comment]
Okay, then let's close that PR and move our discussion to #3225

**Pull request closed without merging**
