### PR TITLE
issues comment API : list, create, edit

### PR DESCRIPTION
**Pull request by iwanbk**
Implements issue comments API as proposed in https://github.com/gogits/gogs/issues/1692#issuecomment-206590786

The API is similar to github API, except:

- ~~the list API still not supporting `since` parameters~~
- edit comment needs `index` query parameter

This PR depend on API client lib PR https://github.com/gogits/go-gogs-client/pull/26

docs

## List comments on an issue

```
GET /repos/:owner/:repo/issues/:index/comments
```

Response

```
Status: 200 OK
Content-Type: application/json
```
```
[
  {
    "id": 4,
    "type": 0,
    "poster": {
      "id": 1,
      "username": "ibk",
      "full_name": "",
      "email": "ibk@xxx.net",
      "avatar_url": "https://secure.gravatar.com/avatar/0d02f30bf8f58f6344ea19fd8e26ad6b"
    },
    "issue_id": 1,
    "commit_id": 0,
    "line": 0,
    "content": "id 3 atau apa hayo?",
    "created": "2016-04-09T11:06:35+07:00",
    "created_unix": 1460174795,
    "commit_sha": ""
  },
  {
    "id": 5,
    "type": 0,
    "poster": {
      "id": 1,
      "username": "ibk",
      "full_name": "",
      "email": "ibk@xxxx.net",
      "avatar_url": "https://secure.gravatar.com/avatar/0d02f30bf8f58f6344ea19fd8e26ad6b"
    },
    "issue_id": 1,
    "commit_id": 0,
    "line": 0,
    "content": "komen no piro yo, soko postman pokoke",
    "created": "2016-04-11T11:37:31+07:00",
    "created_unix": 1460349451,
    "commit_sha": ""
  }]
```

## Create a comment
```
POST /repos/:owner/:repo/issues/:index/comments
```

Parameters

Name    |   Type |  Description
----------  |  ------- | ------------------
content  |  string | the comment

Example
```
{"content":"this is issue comment"}
```

Response

````
Status: 201 Created
Content-Type: application/json
```

````
{
  "id": 9,
  "type": 0,
  "poster": {
    "id": 1,
    "username": "ibk",
    "full_name": "",
    "email": "ibk@xxxx.net",
    "avatar_url": "https://secure.gravatar.com/avatar/0d02f30bf8f58f6344ea19fd8e26ad6b"
  },
  "issue_id": 1,
  "commit_id": 0,
  "line": 0,
  "content": "this is issue comment",
  "created": "2016-04-12T11:18:45+07:00",
  "created_unix": 1460434725,
  "commit_sha": ""
}

```

## Edit a comment

```
PATCH /repos/:owner/:repo/issues/:index/comments/:id
```

Parameters

Name    |   Type |  Description
----------  |  ------- | ------------------
content  |  string | the comment

Example
```
{"content":"metu pora (wis diedit)"}
```

Response

```
Status: 200 OK
Content-Type: application/json
```

````
{
  "id": 8,
  "type": 0,
  "poster": {
    "id": 1,
    "username": "ibk",
    "full_name": "",
    "email": "ibk@xxxx.net",
    "avatar_url": "https://secure.gravatar.com/avatar/0d02f30bf8f58f6344ea19fd8e26ad6b"
  },
  "issue_id": 1,
  "commit_id": 0,
  "line": 0,
  "content": "metu pora (wis diedit)",
  "created": "2016-04-11T11:47:48+07:00",
  "created_unix": 1460350068,
  "commit_sha": ""
}
```

### CODE REVIEW

**Comment by iwanbk** [comment]
i added `since` query string support to list issue comment API

**Comment by graywolf336** [comment]
Any progress on this? I would love to see this and more rest apis added!

**Comment by hhenkel** [comment]
I just tested this locally at our installation and all three API worked for me. Would be good if the code could be reviewed and rebased on the current code.

**Comment by Unknwon** [comment]
Please sign the CLA.

**Comment by iwanbk** [comment]
@Unknwon done, just signed the CLA

**Comment by hhenkel** [comment]
@iwanbk can you also rebase your code against the current state of the develop branch so it is easier for people to test the code.

**Comment by hhenkel** [comment]
@iwanbk any news on getting this up2date? There have been more changes to the upstream code so the chunk of work that needs to be rewritten gets larger and larger. I would really love to see this feature in upstream as that would help me to keep my gogs near the develop branch and ease some pain till #813 is implemented.

**Comment by iwanbk** [comment]
@hhenkel
Will do it tomorrow. Sorry for the delay

**Comment by iwanbk** [comment]
```
@hhenkel
Will do it tomorrow. Sorry for the delay
```
Sorry, can't make it today.
I will do it this friday.

**Comment by Unknwon** [comment]
Just a quick tip while you fix conflict, now Issue and User both uses `*.APIFormat` not `convert.To*(*)` anymore.

**Comment by iwanbk** [comment]
@Unknwon thanks for the tips.

But this PR depend on client side PR at https://github.com/gogits/go-gogs-client/pull/26, the build will failed before that PR getting accepted

**Comment by hhenkel** [comment]
@Unknwon @iwanbk so is this pr in a deadlock situation now?

iwanbk waiting to have the go-gogs-client stuff merged and Unknwon waiting that the code is refactored against the current head?

**Comment by Unknwon** [comment]
@iwanbk sorry for long waiting.

https://github.com/gogits/go-gogs-client/pull/26 has been merged with necessary code cleanup. Please resolve conflict in this PR.

**Comment by iwanbk** [comment]
```
@iwanbk sorry for long waiting.
```
No problem

```
 Please resolve conflict in this PR.
```
Done :)

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
