### PR TITLE
Add check for LDAP group membership

### PR DESCRIPTION
**Pull request by aboron**
Validates the user as before, then uses filter settings to find a list of groups which LDAP users must be a member.
If the user is a member of any of the valid groups, then login is allowed to proceed.
Group base and related attributes are all configurable for maximum flexibility.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thank you!

**Comment by aurel-appsthru** [comment]
Hi, 
I'm very interesting for this fonctionnality. 
But I can not get it to work. 
 
0.11.29 @ 2017-08-15 , windows_amd64_mws


See my screenshot.
See my log below : 

```
> 2017/08/30 14:27:44 [TRACE] LDAP: Dialing with security protocol '1' without verifying: true
> 2017/08/30 14:27:44 [TRACE] LDAP will use BindDN
> 2017/08/30 14:27:44 [TRACE] Search for LDAP user: gogsuser1
> 2017/08/30 14:27:44 [TRACE] LDAP: Bound as BindDN: CN=gogs,OU=Utilisateurs,OU=General,DC=mycompany,DC=com
> 2017/08/30 14:27:44 [TRACE] LDAP: Searching for DN using filter '(&(sAMAccountName=gogsuser1)(objectClass=user))' and base 'DC=mycompany,DC=com'
> 2017/08/30 14:27:44 [TRACE] Binding with userDN: CN=GOGS User 1,OU=Utilisateurs,OU=Support,OU=Admin,DC=mycompany,DC=com
> 2017/08/30 14:27:44 [TRACE] Bound successfully with userDN: CN=GOGS User 1,OU=Utilisateurs,OU=Support,OU=Admin,DC=mycompany,DC=com
> 2017/08/30 14:27:44 [TRACE] Fetching attributes 'sAMAccountName', 'givenName', 'sn', 'mail', 'cn' with filter '(&(sAMAccountName=gogsuser1)(objectClass=user))' and base 'CN=GOGS User 1,OU=Utilisateurs,OU=Support,OU=Admin,DC=mycompany,DC=com'
> 2017/08/30 14:27:44 [TRACE] LDAP: Fetching groups 'member' with filter '(CN=Groupe-Gogs)' and base 'OU=Groupes,OU=Support,OU=Admin,DC=mycompany,DC=com'
> 2017/08/30 14:27:44 [TRACE] LDAP: Group membership test failed [username: gogsuser1, group_member_uid: member, user_uid: GOGS User 1
> 2017/08/30 14:27:44 [ WARN] Failed to login 'gogsuser1' via 'LDAP BindDN': user does not exist [user_id: 0, name: gogsuser1]
```
However, my user's "cn" is in the "member" attribute of the group. ( AD DS 2012 R2 )
It works well when I don't use the group check.
Maybe I misunderstand the query needed. 
Thank you for your help. 


gogs-auth

**Comment by aboron** [comment]
The check is testing the name "gogsuser1" against "GOGS User 1" so it is failing to match. Check the "User attribute Listed in Group" setting, it probably needs to be something else.  Possibly "sAMAccountName".

Also, since it seems you are authenticating against active directory, you can probably avoid using "Verify group membership" entirely and instead just write a "User Filter" that tests for group membership, like:
`(&(objectClass=Person)(memberOf=CN=group-name,OU=users,DC=company,DC=com))`
Substituting in the full DN of the group you are checking membership.

**Comment by aurel-appsthru** [comment]
Thank you for your quick response. 

As my group "member" attribute contains multiple CN like this :   

> CN=GOGS User 1,OU=Utilisateurs,OU=Support,OU=Admin,DC=mycompany,DC=com

I thought that it will search user_uid in group_member_uid ( "GOGS User 1" in "member" attribute.  )
It didn't found.
"sAMAccountName" is the entry I want to use for loging in ("gogsuser1"). 

So, I used your idea with the user filter. 
That works !

Thank you very much.

**Pull request merged**
