### PR TITLE
[Translators Wanted!] Change "Close and comment" to "Comment and close"

### LINKED ISSUE #1831: "close and comment" should be "comment and close"
I think it would make more sense (as a single action) to comment on an issue then close it. At the moment, the "close and comment" button does exactly that - it closes, then comments. This can be hard to tell if the comment was made AFTER the close, and is suggesting a re-open without actually reading the comment. Whereas, if the comment followed by a close is the last comment, it's easy to see there's no commentary after the close! (0.6.9)

### PR DESCRIPTION
**Pull request by JohnMaguire**
This would close #1831 if we could get other translations in this pull request.

### CODE REVIEW

**Comment by tboerger** [comment]
Gogs uses crowdin for handling transpations.

**Comment by JohnMaguire** [comment]
@tboerger Is that something I can handle / does that make this pull request void?

**Comment by tboerger** [comment]
Yes, you can read how it works at http://gogs.io/docs/features/i18n

This makes this pull request obsolete.

**Comment by JohnMaguire** [comment]
Thank you. :)

**Comment by ChangePlaces** [comment]
Thanks anyway :)

**Comment by Unknwon** [comment]
All changes are made and pushed to `develop` branch.

**Pull request closed without merging**
