### PR TITLE
Add pagination to release-page (#2164)

### LINKED ISSUE #2164: Add pagination to releases
All the releases come in one page. I have a git repo with thousands of tags, where it would be appreciated to limit the number of releases to 10 per page.

This lack of pagination causes the relases page to hang for several minutes.

### PR DESCRIPTION
**Pull request by bkcsoft**
This fixes #2164 

Hard-coded to 10 releases per page which is what GitHub does as well :)

### CODE REVIEW

**Comment by bkcsoft** [comment]
@Unknwon for gitea we merged all pagination-templates so they could be integrated anywhere, what do you think about that?

**Comment by Unknwon** [comment]
@bkcsoft that's a good idea, but I have to take a look first..

**Comment by bkcsoft** [comment]
@Unknwon the relevant PR if you wanna have a look :) https://github.com/go-gitea/gitea/pull/73/files

**Comment by Unknwon** [comment]
Closed by https://github.com/gogits/gogs/commit/07801cbf094b55bd848865176dd0eafe99b37ad7.

**Pull request closed without merging**
