### PR TITLE
fix settings/email html&css

### PR DESCRIPTION
**Pull request by makhov**
Before: gogs go git service_old
After: gogs go git service

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

I hate to say this, but please do not change css files, change in .less instead, thanks!

**Comment by makhov** [comment]
@Unknwon Ok. 
I remove code from css and add it to less file.

**Comment by makhov** [comment]
Should I generate new css file and add it to commit?

**Comment by Unknwon** [comment]
Don't have to, I can handle css for you!

**Comment by Unknwon** [comment]
I'll merge soon in terms of other matters, thanks again!

**Comment by Unknwon** [comment]
Merged, thanks again!

**Comment by Unknwon** [comment]
And next time, please PR to `dev` as https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md noted.

**Pull request merged**
