### PR TITLE
Adding myself to translators

### PR DESCRIPTION
**Pull request by rbukovansky**
As you included Czech translation to official distribution, I think I'm missing here.
I know, selfish as hell... ;)

### CODE REVIEW

**Comment by bkcsoft** [comment]
Why did you move Robert and Robin? :confused:

**Comment by Eriner** [comment]
@bkcsoft he didn't, the formatting in his PR is just strange.

**Comment by rbukovansky** [comment]
They are not removed, in my file they were between names beginning with "i" and "j", so I have moved them to correct position... View commit to see they are there...

**Comment by bkcsoft** [comment]
Yeah I noted that. looks good to me :)

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
