### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by gittex**
This PR contains some translation updates:
1) it adds missing translation into german (de_DE)
2) it improves two english texts a little bit

### CODE REVIEW

**Comment by phsmit** [comment]
Also nice improvement for the English

For the German, I believe that those should be submitted here: https://crowdin.com/project/gogs

**Comment by gittex** [comment]
I'm not so familiar with the crowdin tool, but I can't find the missing words or a way to add thoses.

**Comment by phsmit** [comment]
I can't find them either :( Probably @Unknwon or another maintainer has to upload the current English .ini to that service first.

**Comment by Unknwon** [comment]
Thanks your PR!

I would merge this right now, and upload new English version to Crowdin, so for Germen, you would need to copy-paste them to there and I will rebuild new German locale file to Gogs repository.

**Pull request merged**
