### PR TITLE
Referencing issues from commit messages is now possible.

### LINKED ISSUE #462: Controlling issues via commit commands
Like on GitHub and other services, ex. closes #x or fixes #x or reopens #x

### PR DESCRIPTION
**Pull request by EtienneBruines**
Code-wise: the fixing-part of the code now doesn't reference the issue any more, because this is done by the referencing-part of the code, which is called just before.

Fixes #462, #668, #732.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

Simple question:

Would this will produce one reference and one close actions if commit message is `fix #1`?

Because based on the patterns, it seems like reference pattern will also match strings that should be only matched for `fix/fixes` etc. patterns?

**Comment by EtienneBruines** [comment]
It references and closes, yes. This was already the case, and, since a "close" does not reference to an issue, this is what you'd want.

**Comment by Unknwon** [comment]
Cool, I see. Will merge soon in terms of other matters.

BTW, how's your dinner going? :smile:

**Comment by Unknwon** [comment]
Merged, thanks again!

**Pull request merged**
