### PR TITLE
fix error link under preview

### PR DESCRIPTION
**Pull request by raphael10241024**
You can still see the wrong link error under preview .

### CODE REVIEW

**Comment by Unknwon** [comment]
>You can still see the wrong link error under preview .

What does this suppose to mean?

**Comment by raphael10241024** [comment]
Not very useful in fact.. 
But you can view the link while you are previewing the file you are editing and click it  
image

**Comment by raphael10241024** [comment]
The Bug #3561 ,Sorry I forget that

**Comment by Unknwon** [comment]
...thanks

**Pull request merged**
