### PR TITLE
Fix #3314: Cannot edit release with tag name contains slash

### LINKED ISSUE #3314: Cannot edit release with tag name contains slash
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

**For bug reports, please give the relevant info:**

- *Gogs version (or commit ref):* 0.9.48
- *Git version:* 1.8.3.1
- *Operating system:* Linux CentOS 7 64bit
- *Database:* SQLite
- *Can you reproduce the bug at http://try.gogs.io:* Yes --> https://try.gogs.io/zero-x-baadf00d/psychic-soul/releases

## How to reproduce

1. Create a repository
2. Do some commit and create tag "release/xxxxx"
3. Create a release on gogs
4. Click "publish" or "save draft"
5. Back to releases
6. Click "edit" (server ask for basic auth - see screenshoot)
7. Oops: 404 Error

capture

...

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This pull request aim to fix issue #3314 with non flat tagname (ie: release/x.x.x) leading to a 404 error when user trying to edit it.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR, but this is not a valid solution. The correct solution is escape the tag name in HTML with `EscapePound`.

**Comment by 0xbaadf00d** [comment]
Thanks for help. I will apply modifications today.

**Comment by 0xbaadf00d** [comment]
Replacing _/_ with _%2F_ seems not working. Macaron still treat _%2F_ as _/_ before process routing and finally returning a 404 error (I don't even reach the function `EditReleasePost(ctx *context.Context, form auth.EditReleaseForm)`.

**Demonstration:**
https://try.gogs.io/zero-x-baadf00d/psychic-soul/releases/edit/release%2f1.3.1

**Comment by Unknwon** [comment]
Good point.

**Comment by Unknwon** [comment]
Please sign the CLA.

**Comment by 0xbaadf00d** [comment]
Done.

**Comment by 0xbaadf00d** [comment]
I have recreated a PR with a correct commit author email.

**Pull request closed without merging**
