### PR TITLE
Feature #3398: Redefine global mirror interval

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This pull request add new key on `app.ini` to configure the mirror global interval (#3398).

By example, to set mirror global interval to 6 hours rather than 24 :
```
[mirror]
GLOBAL_INTERVAL = 6
```

### CODE REVIEW

**Comment by Unknwon** [comment]
Commented on #3398.

**Comment by 0xbaadf00d** [comment]
The variableis now renamed to `DEFAULT_INTERVAL`

**Comment by Unknwon** [comment]
I think the `Mirror` should put after [this line](https://github.com/0xbaadf00d/gogs/blob/bb3732e082a897bc5ef049de3b1c2bb563cd7306/modules/setting/setting.go#L208), and load with another `else if` before [api](https://github.com/0xbaadf00d/gogs/blob/bb3732e082a897bc5ef049de3b1c2bb563cd7306/modules/setting/setting.go#L499) section. This also requires you add a `[mirror]` section after `[git]` in `conf/app.ini` file.

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
