### PR TITLE
Update .gopmfile

### PR DESCRIPTION
**Pull request by fanningert**
Add missing dependencies

### CODE REVIEW

**Comment by Unknwon** [comment]
Next time `develop` branch please :D

**Comment by fanningert** [comment]
Sorry, my mistake

**Comment by variablenix** [comment]
I think the following is a result of missing crypto/x dependencies with recent builds. Please advise. 

`modules/ssh/ssh.go:20:2: cannot find package "golang.org/x/crypto/ssh" in any of:
	/tmp/yaourt-tmp-user/aur-gogs-git/src/build/go/src/golang.org/x/crypto/ssh (from $GOROOT)
	/tmp/yaourt-tmp-user/aur-gogs-git/src/build/src/golang.org/x/crypto/ssh (from $GOPATH)`

**Comment by Unknwon** [comment]
@variablenix do `go get golang.org/x/crypto/ssh`

**Comment by fanningert** [comment]
@variablenix Sorry I forgot to update the gogs-git package. Now the current package version is corrected.
Now I only get this error on compile. #1959

**Comment by variablenix** [comment]
@fanningert @Unknwon No worries, the build is now successful. Thank you both very much!

**Pull request merged**
