### PR TITLE
Update for the french langage file

### PR DESCRIPTION
**Pull request by AmauryCarrade**
- Updated some translations so the texts are in a better French language.
- Fixed typos and French errors in the translations.
- Changed a few terms to be more comprehensible for French developers (as example the translations for « repositories », « issues », « milestones », « fork »—the previous translations were never used in the real world).
- Fixed French typography errors (as it's not the same as the English one).

(French is my native language.)

### CODE REVIEW

**Comment by xxxtonixxx** [comment]
You must do re-PR in develop branch... :+1:

**Comment by AmauryCarrade** [comment]
Oh, I forgot to select the development branch. Oops. I'll re-send this PR after fixing the few things suggested by @MaxenceG2M.

**Comment by andreynering** [comment]
Actually, translation are made in Crowdin:

- https://gogs.io/docs/features/i18n
- https://crowdin.com/project/gogs

**Comment by Unknwon** [comment]
....What is going wrong with GitHub... it is keep telling me @andreynering has commented on this.. like 3 times..

**Comment by andreynering** [comment]
@unkwon https://twitter.com/githubstatus

**Pull request closed without merging**
