### PR TITLE
Fixed a typo: .ssh/authorized_key -> .ssh/authorized_keys

### PR DESCRIPTION
**Pull request by xaionaro**

### CODE REVIEW

**Comment by xaionaro** [comment]
I made a mistake in the first commit here and fixed and by the second one. Should I squash this commits?

**Comment by Unknwon** [comment]
Thanks your work, but we do not update locale files in source file.  :scream:

Please see [README](https://github.com/gogits/gogs#overview).

**Comment by xaionaro** [comment]
> Thanks your work, but we do not update locale files in source file. ￼
> 
> Please see README.

Well… I didn't get what I done wrong and what means "locale files in source file". I don't understand what should I do to fix that typo, but I hope somebody (who is smarter than me) will understand that and fix the typo. [no sarcasm]

**Comment by Unknwon** [comment]
Those files are generated automatically from https://crowdin.com/project/gogs . Except `en-US.ini` file.

**Pull request closed without merging**
