### PR TITLE
For LDAP user sync #1268 

### PR DESCRIPTION
**Pull request by lafriks**
Still have to create cron job for regular interval sync

### CODE REVIEW

**Comment by Lafriks** [comment]
Created new cron job with option to update existing user data or just creating new users.
Probably one thing to think about if option not to update users is set probably it would still be needed to deactivate users that are not in LDAP server anymore. Currently it only deactivates users if UpdateUsers option is set to true

**Comment by ptman** [comment]
Have you thought about updating data on login?

**Comment by Lafriks** [comment]
Do you mean updating only current users name/surname/email that is logging in or all users?

**Comment by ptman** [comment]
Only current

**Comment by barracks510** [comment]
Can you incorporate an option to disable the removal of old users?

**Comment by Lafriks** [comment]
Old users are not removed, just disabled

**Comment by Lafriks** [comment]
Any progress on merging this?

**Comment by lafriks** [comment]
?

**Comment by Unknwon** [comment]
image

**Comment by strk** [comment]
@ptman would you be up to port this to Gitea ?

**Comment by lafriks** [comment]
Pull request have been ported to Gitea, so if you are interested in it get latest changes from there

**Pull request closed without merging**
