### PR TITLE
Fixed #2416

### LINKED ISSUE #2416: DisableMinimumKeySizeCheck is not a field of struct type interface {}
template: admin/config:82:38: executing "admin/config" at <.Service.DisableMini...>: DisableMinimumKeySizeCheck is not a field of struct type interface {}

I get that when I try to enter the configuration in "latest" docker tag. If I use 0.8.10 as docker tag, it works.
I chose blank ssh port and sqlite for db. Otherwise everything totally default.

### PR DESCRIPTION
**Pull request by exmex**

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks your PR!

But commits and changes look very confusing?

**Comment by Unknwon** [comment]
I think this PR was a mistake?

**Comment by exmex** [comment]
Yes it was. Somehow the company intern files got pushed in here T_T

**Comment by Unknwon** [comment]
Not the first time :joy:

**Pull request closed without merging**
