### PR TITLE
Fix admin configuration new ui

### PR DESCRIPTION
**Pull request by sapk**
capture d ecran_2015-09-26_01-52-27

### CODE REVIEW

**Comment by Unknwon** [comment]
Hmm.. thanks. But you should really discuss first with this page, there are reasons to no done by PR for some pages.

And Gogs does not use `gogs.css` but `gogs.min.css` currently(sorry about confusion).

Also, HTML indention is kind of messed up. All indent should be exactly 1 tab/2 spaces.

**Comment by sapk** [comment]
I have update both gogs.css and gogs.min.css ^^. 
I will fix indent.

**Comment by Unknwon** [comment]
After this one, you can work on admin dashboard, but please stop there and discuss for next page :)

**Comment by Unknwon** [comment]
This one has conflict.

**Comment by Unknwon** [comment]
@pecigonzalo I can't merge because no response.

**Comment by pecigonzalo** [comment]
@Unknwon thanks for the quick response
@sapk

**Comment by sapk** [comment]
@Unknwon Sorry i have rebased it after you report it but didn't mention it. If i remember the only blocking file are the .css file that need to be regenrated after the update of the .less. Will redo-it and mention it

**Comment by Unknwon** [comment]
@sapk OK... Hmm, how about `discard` changes for `.css` and I'll regenerated after merged the PR.

**Comment by sapk** [comment]
@Unknwon : In fact i do not need  to modify the less file since the change made in https://github.com/gogits/gogs/pull/1769 are sufficient.

**Comment by Unknwon** [comment]
Very well :tada:

**Pull request merged**
