### PR TITLE
Fixed a typo: .ssh/autorized_key -> .ssh/authorized_key

### PR DESCRIPTION
**Pull request by xaionaro**

### CODE REVIEW

**Comment by xaionaro** [comment]
Damn. I fixed one typo, but missed another one. Should be plural: "authorized_keys" (not "authorized_key").

**Comment by xaionaro** [comment]
Will one more pull request help to fix the second bug?

**Comment by lunny** [comment]
OK. Please.

**Comment by xaionaro** [comment]
Done: https://github.com/gogits/gogs/pull/1230

Sorry for my inattentiveness…

**Comment by Unknwon** [comment]
Thanks your work, but we do not update locale files in source file.  :scream:

**Pull request merged**
