### PR TITLE
Fixing Macaron commit hash. Fixes #3690

### LINKED ISSUE #3690: wrong dependency version in glide.lock   and .gopmfile
- Gogs version (or commit ref): 
  master HEAD
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Not relevant

gopkg.in/macaron.v1 locked at  7564489a79f3f96b7ac8034652b35eeebb468eb4 , but  no such ref exist. Compared go-macaron/macaron local copy refs against github history, looks all commits after 9eb6aa1af19e4076afc0763adeb65aab610a8c6e was replaced ( git push -f  or something worse ? )

### PR DESCRIPTION
**Pull request by saboya**
This fixes #3690

### CODE REVIEW

**Comment by samuelson** [comment]
+1 fixed the issue for me

**Comment by eljojo** [comment]
is this really working?
After applying this I can successfully ``glide install``, but now I cannot build: 

```
$ go build
# github.com/gogits/gogs/models
models/access.go:84: cannot use x (type *xorm.Engine) as type Engine in argument to accessLevel:
	*xorm.Engine does not implement Engine (wrong type for Where method)
		have Where(string, ...interface {}) *xorm.Session
		want Where(interface {}, ...interface {}) *xorm.Session
models/access.go:94: cannot use x (type *xorm.Engine) as type Engine in argument to hasAccess:
	*xorm.Engine does not implement Engine (wrong type for Where method)
		have Where(string, ...interface {}) *xorm.Session
		want Where(interface {}, ...interface {}) *xorm.Session
models/access.go:245: cannot use x (type *xorm.Engine) as type Engine in argument to r.recalculateAccesses:
	*xorm.Engine does not implement Engine (wrong type for Where method)
		have Where(string, ...interface {}) *xorm.Session
		want Where(interface {}, ...interface {}) *xorm.Session
models/action.go:194: cannot use x (type *xorm.Engine) as type Engine in argument to newRepoAction:
...
```

**Comment by saboya** [comment]
@eljojo That's another issue, related to xorm.

**Comment by samuelson** [comment]
+1

**Comment by andreynering** [comment]
Xorm issue addressed at #3756

**Comment by atsepkov** [comment]
When will this fix be merged? I've been applying it manually every time I do a git clone of gogs on my test box, without it gogs won't build, so the current version is effectively broken.

**Comment by Unknwon** [comment]
Thanks! Closed by another commit.

**Pull request closed without merging**
