### PR TITLE
Fix mention in comments like (@dblk)

### PR DESCRIPTION
**Pull request by DblK**
It a small fix for issue #3649.

### CODE REVIEW

**Comment by LefsFlarey** [comment]
Looks good, though I don't think the expected behaviour is somethinglikethis@dblk

**Comment by DblK** [comment]
Thank for your reply. I will try to fix the later example.
I didn't know the negative lookbehind. Will have a look for Golang and make another commit.

**Comment by DblK** [comment]
The RegExp you suggested does not seems to work in Golang.
I need to find another trick.

**Comment by LefsFlarey** [comment]
@DblK, as you have reported, apparently GoLang does not support lookaround. As such, here's an alternative that ***should*** work.

[`(?:[^\w])@([0-9a-zA-Z-_\.]+)`](https://regex101.com/r/zM8dC4/2)

If extraction of the user is important, extract from group 1 through `\1` or `$1`.

**Comment by DblK** [comment]
The above RegExp does not work either. I fixed in another way.

**Comment by LefsFlarey** [comment]
Alright, that seems to work along the same principles too, but CI kinda failed there right there...

**Comment by xor-gate** [comment]
👍 looking good

**Comment by Unknwon** [comment]
Thanks!

**Pull request merged**
