### PR TITLE
Add ROW_FORMAT=DYNAMIC when creating table for supports mysql 5.6 (fi…

### PR DESCRIPTION
**Pull request by m2nlight**
…x #4894)

NOTE: I added codes to xorm for supports `ROW_FORMAT=DYNAMIC`.

### CODE REVIEW

**Comment by Unknwon** [comment]
Thank for the PR!

I wonder the changes under `/vendor` directory, are these changes been accepted by upstream (i.e. "github.com/go-xorm/xorm") or only modified locally for things to work?

**Comment by m2nlight** [comment]
Wellcome back! I'm sorry about the utf8mb4 lenght error in some older mysql version. Because  the upstreams is NOT accepted the code, yet. So, I recommend close this PR and change the MySQL connection string from UTF8MB4 back to UTF8. Looking forward to gogs' new release.

**Comment by Unknwon** [comment]
>I'm sorry about the utf8mb4 lenght error in some older mysql version.

Hmm, it's not your fault.

> Because the upstreams is NOT accepted the code, yet.

Have you sent PR to the upstream yet?

**Comment by m2nlight** [comment]
The upstream PR:
https://github.com/go-xorm/core/pull/36
https://github.com/go-xorm/xorm/pull/798

**Comment by Unknwon** [comment]
Hmm... I still think modify files in vendor creates huge confusion in the future. It is possible to do the same task via SQL command? So Gogs could have a temp fix for MySQL specifically (which is possible) and remove when upstream is updated.

**Comment by m2nlight** [comment]
If SQL command:
```
SET GLOBAL innodb_file_per_table = ON,
       innodb_file_format = Barracuda,
       innodb_large_prefix = ON;
```

Append ` ROW_FORMAT=DYNAMIC` to each create/alter table statement.
Maybe set [innodb_large_prefix = ON](https://help.aliyun.com/knowledge_detail/41707.html) (https://github.com/gogits/gogs/issues/5066)

**Comment by Unknwon** [comment]
Looks like one last PR need to be merged before success :D

**Comment by Unknwon** [comment]
Hi @m2nlight , both PRs are now merged by upstream, could you update this one accordingly?

**Comment by m2nlight** [comment]
It's a good news! I updated this PR before. But I am on holiday for a few days. Sorry I have no computer to test the update on this weekend.

**Comment by Unknwon** [comment]
No worries, enjoy your time!

**Comment by Unknwon** [comment]
I have updated the vendors, so only two files (`models/models.go`, `scripts/mysql.sql`) need to be updated in the PR.

**Comment by Unknwon** [comment]
Is it good enough to be merged?

**Comment by m2nlight** [comment]
Yes, can you test it ?

**Comment by Unknwon** [comment]
I couldn't get the "767 bytes" error but as long as I test on MySQL 5.7 it doesn't break, merging...

**Pull request merged**
