### PR TITLE
Show issue/PR number on title

### PR DESCRIPTION
**Pull request by andreynering**
Instead of:

```
My Issue - Gogs: Go Git Service
```

Title will now be:

```
#5 - My Issue - Gogs: Go Git Service
```

### CODE REVIEW

**Comment by LefsFlarey** [comment]
That isn't normal GitHub behaviour though, is it?

**Comment by andreynering** [comment]
@LefsFlarey GitHub shows the number *after* the title. Gogs currently doesn't show. I prefer the number *before* so it's easy to see and refer in commits.

**Comment by LefsFlarey** [comment]
Then I guess it depends how much @Unknwon wants this, before or after the title.

**Comment by strk** [comment]
@andreynering Could you please migrate this to go-gitea/gitea ? I was just hit by the lack of issue number and would like to see this PR merged :)

**Comment by strk** [comment]
For reference, github does it like this:
```<title>Show issue/PR number on title by andreynering · Pull Request #3757 · gogits/gogs</title>```

**Comment by andreynering** [comment]
See https://github.com/go-gitea/gitea/pull/60

Em sex, 4 de nov de 2016 05:06, Sandro Santilli <notifications@github.com>
escreveu:

**Pull request closed without merging**
