### PR TITLE
Added repository remove option to API

### PR DESCRIPTION
**Pull request by soudy**
I wanted to implement some more features like update repo, remove user and update user but that would cause some difficulties having to work on [go-gogs-client](https://github.com/gogits/go-gogs-client).

usage is as following:

## Remove repository
    DELETE /repos/:owner/:reponame

#### Example
     $ curl -X DELETE -H 'Authorization: token TOKEN_ID' https://try.gogs.io/api/v1/repos/soud/MyRepo

#### Response
```
Status: 204 No Content
Content-Type: application/json
```

### CODE REVIEW

**Comment by tboerger** [comment]
I personally prefer restful URLs, your approach gets aeay from that even more :(

**Comment by soudy** [comment]
@tboerger what do you mean with 'restful url'? I believe the url is pretty restful

**Comment by tboerger** [comment]
No, it's absolutely not restful. If it's a route to delete a resource it should be DELETE /repos/:reponame. Even another approach that is more restful than yours, but not the best for restful perspective, should be GET /repos/:reponame/remove.

**Comment by tboerger** [comment]
For the reference, there it gets explained pretty well http://guides.rubyonrails.org/routing.html#resources-on-the-web

**Comment by soudy** [comment]
@tboerger ah yes I agree that's better, I'll get onto that. thanks for the feedback

**Comment by Unknwon** [comment]
Thanks your PR!

Gogs's API design mostly follow the GitHub style, see reference: https://developer.github.com/v3/repos/#delete-a-repository

**Comment by soudy** [comment]
@Unknwon ok, so you'd prefer `/repos/:owner/:repo` over `/repos/:repo`?

**Comment by Unknwon** [comment]
@soudy yes, otherwise, how would you delete a organization repository?

**Comment by soudy** [comment]
@Unknwon good point - I forgot about organizations

**Comment by Unknwon** [comment]
GitHub has pretty good documentation for APIs :smile:

**Comment by soudy** [comment]
@Unknwon I've updated it to work with organisations

**Comment by Unknwon** [comment]
> perhaps I should call GetOwner on the repo so Owner isn't null, what do you think?

No, `IsOwnedBy` only compare ID which can/should never be null.

**Comment by soudy** [comment]
@Unknwon I was talking about the Owner: section in the JSON response

**Comment by Unknwon** [comment]
@soudy 

1. See https://github.com/gogits/gogs/blob/master/routers/api/v1/repo_file.go#L23-L27 for an example of response. (`ok` is only been used for UI-related APIs)
2. Based on reference, https://developer.github.com/v3/repos/#response-11 , status 204 should be presented and no content.

**Comment by Unknwon** [comment]
PS: response a status without content can use `ctx.Status(204)`.

**Comment by soudy** [comment]
@Unknwon thanks for the pointers, I've updated it to Github's standars now

**Comment by Unknwon** [comment]
Thanks! Looks better now, will merge soon.

**Comment by Unknwon** [comment]
Thanks again, merging.

**Pull request merged**
